// Rarity → Pokéball reel symbol (seeded defaults; assets generated by
// scripts/process-balls.mjs). Cosmetic only — the won card is decided server-side
// (spec §8). The admin-managed Ball entity is a separate future plan.
import type { Rarity } from '@/app/claw/packs-data';

export const BALL_BY_RARITY: Record<Rarity, string> = {
  Legendary: '/images/balls/master.webp',
  Epic: '/images/balls/luxury.webp',
  Rare: '/images/balls/ultra.webp',
  Uncommon: '/images/balls/great.webp',
  Common: '/images/balls/poke.webp',
};

export const DECOY_BALLS: string[] = [
  '/images/balls/decoy-premier.webp',
  '/images/balls/decoy-timer.webp',
  '/images/balls/decoy-dive.webp',
  '/images/balls/decoy-nest.webp',
  '/images/balls/decoy-friend.webp',
  '/images/balls/decoy-love.webp',
  '/images/balls/decoy-net.webp',
];

export function ballSrc(rarity: Rarity): string {
  return BALL_BY_RARITY[rarity];
}
