// GENERATED by scripts/snapshot-prod-catalog.mjs — do not hand-edit.
// A read-only snapshot of the LIVE production catalog (https://polycards.gg), taken so the
// E2E suite exercises the real packs and real cards instead of invented ones.
// Re-run the script after an operator changes the prod catalog.
//
// Cards carry `display_myr` (the RM figure prod shows), not raw USD FMV: the
// public storefront only exposes the displayed price. seed-e2e-fixtures.ts
// converts it back with the same FX rate + multiplier it seeds, so a locally
// seeded card renders the same RM as production.

export interface ProdCatalogCard {
  handle: string;
  name: string;
  set: string;
  grader: string;
  grade: string;
  display_myr: number;
  image: string;
  slab_image: string | null;
  pokemon_dex: number | null;
  sprite_image: string | null;
}

export interface ProdCatalogPack {
  slug: string;
  title: string;
  price: number;
  buyback_percent: number;
  image: string;
  display_image: string | null;
  rank: number;
  cards: { handle: string; rarity: string }[];
}

/** ISO timestamp of the snapshot, for staleness triage. */
export const PROD_CATALOG_CAPTURED_AT = "2026-08-17T07:31:26.315Z";
export const PROD_CATALOG_SOURCE = "https://polycards.gg";

export const PROD_CARDS: ProdCatalogCard[] = [
  {
    "handle": "rowlet-290-sm-p-psa-10-4683337",
    "name": "Rowlet #290/SM-P",
    "set": "SM-P",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 10786.99,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-2c360498900e532323e7c153b694fda976ac27808fef1b73c5778d95b5338d92-1600-01KZPBZPFBBE36CH8P463J1FE2.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-rowlet-290-sm-p-psa-10-4683337-65c1f188-01KZPC9ZGDG9TZRQGRQX6QT1GC.webp",
    "pokemon_dex": 722,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-722-normal-01KX3XMM9N2219XRAZ386RH98P.gif"
  },
  {
    "handle": "hoopa-155-xy-p-psa-10-4188987",
    "name": "Hoopa #155/XY-P",
    "set": "XY-P",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 10239.06,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-30eb9e0575fc6dc450ac1dd508bb173c81eede5f900045461b530460d6484ea8-1600-01KZE65VY2H5DJ10XNT56EV114.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-hoopa-155-xy-p-psa-10-4188987-67a98e2a-01KZE6S5RD50TPG01K963W4GCW.webp",
    "pokemon_dex": 720,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-720-normal-01KX3XMK93MT26J3PJ0TSPSBH6.gif"
  },
  {
    "handle": "reshiram-ex-166-psa-10-10026819",
    "name": "Reshiram ex #166",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 2451.6,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-jq63fh7urcftkih3-1600-01KZE61KAH4H6PJ938H3A4E4E0.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-reshiram-ex-166-psa-10-10026819-c314e588-01KZE6SYP02H44Z125NZ0AM7MM.webp",
    "pokemon_dex": 643,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-643-normal-01KX3XJXY9F7BBW7MMC4R0RAB7.gif"
  },
  {
    "handle": "pikachu-205-psa-10-4447679",
    "name": "Pikachu #205",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 2378.05,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-4c4muvlabcukcqrm-1600-01KZG3NM3QWYE78068DDGSSXCK.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-pikachu-205-psa-10-4447679-e2eb124f-01KZGKKFWMYN33J1YNV8T4VTFT.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "detective-pikachu-98-sv-p-psa-10-5873374",
    "name": "Detective Pikachu #98/SV-P",
    "set": "SV-P",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 2298.52,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-52f0cb7754ab042e5b1206cd05620e562208dab592ec6d65b60e628c26c737c1-1600-01KZE61ES2XTZHVX9VC2X5Z4FD.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-detective-pikachu-98-sv-p-psa-10-5873374-9a855b69-01KZE6T0M6QTYV7BQ06MKGYHET.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "team-rocket-s-moltres-ex-124-psa-10-9090613",
    "name": "Team Rocket's Moltres ex #124",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 906.41,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-qlucawlmsrfl4b4t-1600-01KZG3N22X0QDZQDDB7C17AVXJ.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-team-rocket-s-moltres-ex-124-psa-10-9090613-8837b20a-01KZGKKR6V6TZARN5DNADQX8H7.webp",
    "pokemon_dex": 146,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-146-normal-01KX3XBB6BQJ2D2SQW5SET8VMC.gif"
  },
  {
    "handle": "glaceon-vstar-gg40-psa-10-4637096",
    "name": "Glaceon VSTAR #GG40",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 882.58,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-cd75c84cf7d178d23d8ab220800389cc0c970863f57951f33abd62b049670bb1-1600-01KZE64QFQDPD48FEQ4S2GZF5P.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-glaceon-vstar-gg40-psa-10-4637096-ffa6644b-01KZE6TH8KTR1SR9VYZ2H7GC8E.webp",
    "pokemon_dex": 471,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-471-normal-01KX3XG9SWYR4ZCX45ZKX2CSJK.gif"
  },
  {
    "handle": "pikachu-zekrom-gx-41-psa-10-4118507",
    "name": "Pikachu & Zekrom GX #41",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 851.1,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-qkrhnbre4jrm5f22-1600-01KZE60TZA41P81B6HNAQTKHGB.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-pikachu-zekrom-gx-41-psa-10-4118507-b019ba14-01KZE6TJ9TWSVQBHSFAXSQ6R5J.webp",
    "pokemon_dex": 644,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-644-normal-01KX3XJYBFASCKM8EKGDBCKBAH.gif"
  },
  {
    "handle": "mega-latias-ex-88-psa-10-10117332",
    "name": "Mega Latias Ex #88",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 453.55,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-tr3hgpef742ogkbw-1600-01KZNQ7TM9XQQWG83AV52XG0VB.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-mega-latias-ex-88-psa-10-10117332-9f7fb813-01KZNZY3YR0KYNR8FXBKV0XRGE.webp",
    "pokemon_dex": 380,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-380-normal-01KX3XEW6E5Y4CPRFVNS9R6Z18.gif"
  },
  {
    "handle": "eevee-ex-224-psa-10-8054200",
    "name": "Eevee Ex #224",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 448.3,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-ttclm6eg5c753sda-1600-01KZGWXXV8NVBZJAT6H5S7RGCD.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-eevee-ex-224-psa-10-8054200-e3cb7773-01KZGX9G3J3DY0THDM1KGSTNBQ.webp",
    "pokemon_dex": 133,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-133-normal-01KX3XB549917ZHSWSF2MNMPX0.gif"
  },
  {
    "handle": "keldeo-ex-169-psa-10-9692268",
    "name": "Keldeo Ex #169",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 441.93,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-kopusud7mpdz2e3t-1600-01KZNQ4R1223TQP1B9BNY7S02P.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-keldeo-ex-169-psa-10-9692268-60619c83-01KZP00MN2PHQJ18GJW5VNJWPJ.webp",
    "pokemon_dex": 647,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-647-normal-01KX3XJZQEFA50WJDHVPESQNWQ.gif"
  },
  {
    "handle": "mega-clefable-ex-112-psa-10-11760300",
    "name": "Mega Clefable ex #112",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 429.03,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-a36s5nt73ud2yajc-1600-01KZNQCJVYR5GN1XE1M96B1S34.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-mega-clefable-ex-112-psa-10-11760300-36d6b140-01KZNZTRT4A35SX9YPDX6F5VTR.webp",
    "pokemon_dex": 36,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-36-normal-01KX3X9VG9DCHRS7CCWQW99B3Z.gif"
  },
  {
    "handle": "sawsbuck-92-psa-10-9683082",
    "name": "Sawsbuck #92",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 390.88,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-cyasbww73uj4eh4t-1600-01KZNQ462403MNWSW3081D5GN4.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-sawsbuck-92-psa-10-9683082-651c2454-01KZP013SEGNM22FGQP4C90PDY.webp",
    "pokemon_dex": 586,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-586-normal-01KX3XJ3SGDE0F87T5R4BRHC7R.gif"
  },
  {
    "handle": "lillipup-153-psa-10-9688434",
    "name": "Lillipup #153",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 327.93,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-lvxpwcbjpx3nppqx-1600-01KZNQ4C9C4Y7PVBHS90YPJPB0.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-lillipup-153-psa-10-9688434-44385b5a-01KZP00Y1MC7SVE3NRB5AWV6AW.webp",
    "pokemon_dex": 506,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-506-normal-01KX3XGTQMJMW68F2ZGVAYMV4P.gif"
  },
  {
    "handle": "drampa-83-psa-10-6281530",
    "name": "Drampa #83",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 294.19,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-f18654b2af28a61abb10e66e353cb3621512f9a5143ced844cf32baf04f63103-1600-01KZE6053C9D4YZP71V0R2BWFB.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-drampa-83-psa-10-6281530-de6486c4-01KZE6VJXQV4M7HBGER8RKY0R5.webp",
    "pokemon_dex": 780,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-780-normal-01KX3XNSTJPCWQX15CR7QHBTJS.gif"
  },
  {
    "handle": "sprigatito-75-psa-10-4947432",
    "name": "Sprigatito #75",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 274.58,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-5ppelafphy6hr4df-1600-01KZE65TDT6NQ1ZGA4BHGPCC7Q.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-sprigatito-75-psa-10-4947432-bed0fb38-01KZE6VCD253P5EF5SNTHSPMAT.webp",
    "pokemon_dex": 906,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-906-normal-01KX3XQZ5JB9N1X9G6J63TR42R.gif"
  },
  {
    "handle": "musharna-122-psa-10-9683004",
    "name": "Musharna #122",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 269.77,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-hfw5zgzkawytv4gz-1600-01KZNQ5R10JGJHK3HQZRWT1YX6.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-musharna-122-psa-10-9683004-17ebfc42-01KZNZZVR5NEZK5AT8NYS23HJT.webp",
    "pokemon_dex": 518,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-518-normal-01KX3XH0A9K0Z1K2H8NXTB23WG.gif"
  },
  {
    "handle": "darmanitan-99-psa-10-9681337",
    "name": "Darmanitan #99",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 269.68,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-kp3a7qzhih543fed-1600-01KZNQ56S12419D8MP77HMPCYP.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-darmanitan-99-psa-10-9681337-58af3e81-01KZP009DTPA5MTVS20J1Q8P5Y.webp",
    "pokemon_dex": 555,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-555-normal-01KX3XHJS1P834S5WS1RFZX11R.gif"
  },
  {
    "handle": "darumaka-98-psa-10-9681336",
    "name": "Darumaka #98",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 263.55,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-2ltrhmg5abjfmnkg-1600-01KZNQ5SFBWY0NKZ5YCZF5CB6P.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-darumaka-98-psa-10-9681336-2c578d93-01KZNZZSPA7NK44KT2GYGXN8D6.webp",
    "pokemon_dex": 554,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-554-normal-01KX3XHJ9QT06N1691A1ZMVB20.gif"
  },
  {
    "handle": "amoonguss-96-psa-10-9681335",
    "name": "Amoonguss #96",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 262.62,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-5fn2ra26wshssin5-1600-01KZNQBJGDNKQFDJEQGADNCQF4.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-amoonguss-96-psa-10-9681335-5b460bda-01KZNZVHA71C1PWX1SHW43B553.webp",
    "pokemon_dex": 591,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-591-normal-01KX3XJ656M7VWXB0TB8YP9TQ5.gif"
  },
  {
    "handle": "pikachu-291-sv-p-psa-10-11750071",
    "name": "Pikachu #291/SV-P",
    "set": "SV-P",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 262.32,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-ucg2txd3tvcskw44-1600-01KZE5ZNRBMEG4GT5F2JDMF40V.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-pikachu-291-sv-p-psa-10-11750071-f8638aa9-01KZE6V4F1HWH26R1NEP6F988J.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "vanillite-108-psa-10-9683091",
    "name": "Vanillite #108",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 260.26,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-widuhyocaattrlby-1600-01KZNQ44ECRAKZHGBG6THRGW49.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-vanillite-108-psa-10-9683091-3c285ec7-01KZP014X70Z8JCRN28JWZGV89.webp",
    "pokemon_dex": 582,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-582-normal-01KX3XJ15GBG2ZGGE8G0DEGPS2.gif"
  },
  {
    "handle": "serperior-ex-167-psa-10-9647339",
    "name": "Serperior ex #167",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 259.87,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-eah3r47b5bu5nc3j-1600-01KZNQ71YFEX6GXPB4A3E2XDJ3.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-serperior-ex-167-psa-10-9647339-77fa2541-01KZNZYJM6W9KS6XFMSH8WAT71.webp",
    "pokemon_dex": 497,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-497-normal-01KX3XGPHB2VNP0YX493ZF4Y5K.gif"
  },
  {
    "handle": "zebstrika-112-psa-10-9683095",
    "name": "Zebstrika #112",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 210.84,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-yf52gqlcqbkvg6da-1600-01KZNQ3X00E0SBBYNAX6WMBC7B.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-zebstrika-112-psa-10-9683095-4d82ada6-01KZP01AAKB2JF9X5XVA841NGP.webp",
    "pokemon_dex": 523,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-523-normal-01KX3XH2M7BXD7SCBGPKDBD5RM.gif"
  },
  {
    "handle": "zacian-87-psa-10-10602360",
    "name": "Zacian #87",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 190.24,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-jm5poxijcfh57kuv-1600-01KZGWXBZBR23ATBR4E6Z98JBA.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-zacian-87-psa-10-10602360-1ec3979a-01KZGX9WKHKCC1H6RG8FTAJ4EG.webp",
    "pokemon_dex": 888,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-888-normal-01KX3XQNQE3EAG19Y7HF6B73DK.gif"
  },
  {
    "handle": "spearow-74-psa-10-10117514",
    "name": "Spearow #74",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 186.32,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-ux7ccvrmup4wua5k-1600-01KZNQ818E15SPN20D26WVAG72.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-spearow-74-psa-10-10117514-f90847ca-01KZNZXYF91H0QT6B12B038J65.webp",
    "pokemon_dex": 21,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-21-normal-01KX3X9NF0BJF3SZABY5V7Q6AT.gif"
  },
  {
    "handle": "klawf-88-psa-10-4708204",
    "name": "Klawf #88",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 183.82,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-iyt4x5nqpz3tgmju-1600-01KZE603TKBNJT5EA3CKDJ1ZWF.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-klawf-88-psa-10-4708204-5df11c0a-01KZE6WXTM52XMC3JGW4ZJ442W.webp",
    "pokemon_dex": 950,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-950-normal-01KX3XRMBB5HTF363E3D51J9GF.gif"
  },
  {
    "handle": "decidueye-ex-12-psa-10-11748931",
    "name": "Decidueye ex #12",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 181.37,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-c2gdejyigzu6iia2-1600-01KZNQCBVYWXNG7MEG8TF594F7.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-decidueye-ex-12-psa-10-11748931-bf2a9929-01KZNZTX22NDRPDRQYBCEA8JHJ.webp",
    "pokemon_dex": 724,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-724-normal-01KX3XMNE404HFKVVGMQ4SYQG4.gif"
  },
  {
    "handle": "munna-121-psa-10-9683003",
    "name": "Munna #121",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 180.24,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-vtlfflurk4kmj4ds-1600-01KZNQBEN4CAVR8PJ7RJTVQTBY.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-munna-121-psa-10-9683003-41044123-01KZNZVN1GBWGAKHFP2SZEN5Q8.webp",
    "pokemon_dex": 517,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-517-normal-01KX3XGZTZEMN8GRY7D4G18WN0.gif"
  },
  {
    "handle": "mega-absol-ex-79-psa-10-10117520",
    "name": "Mega Absol Ex #79",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 179.21,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-bfi4cg6c3zzthg7x-1600-01KZNQ7XZ1EP4VWQ0009YCD4ZN.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-mega-absol-ex-79-psa-10-10117520-92d31fe9-01KZNZY0RZSR0YKM3000RWF9RE.webp",
    "pokemon_dex": 359,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-359-normal-01KX3XEJ38YV5ZRH4VZEA2KW71.gif"
  },
  {
    "handle": "pikachu-227-s-p-psa-10-4199649",
    "name": "Pikachu #227/S-P",
    "set": "S-P",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 22380.66,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-ial7gcbhnvqaarnq-1600-01KZGWXF3VE0858JNCSYASZRT9.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-pikachu-227-s-p-psa-10-4199649-ecbd022e-01KZGX9SQC3FMJ3ZABM7C79DK6.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "mewtwo-1st-edition-118-psa-10-3507074",
    "name": "Mewtwo [1st Edition] #118",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 20929.85,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-2rinhfgsevyfhjox-1600-01KZE64EGKME5ARMWGH5MJQET4.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-mewtwo-1st-edition-118-psa-10-3507074-058ded87-01KZE6RQ3T03PH7AWRMV5ZXRWY.webp",
    "pokemon_dex": 150,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-150-normal-01KX3XBD78G0BCF0Q933SWTJ18.gif"
  },
  {
    "handle": "umbreon-vmax-215-psa-10-2513024",
    "name": "Umbreon VMAX #215",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 20598.74,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-tbzk7g5d36blsr7e-1600-01KZG46JY0YGXP41M22E8DPW00.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-umbreon-vmax-215-psa-10-2513024-e120cac0-01KZGKK8JQZFNGHNEKA09TQYWP.webp",
    "pokemon_dex": 197,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-197-normal-01KX3XC3E6BN5T8WZWJ95A3WA7.gif"
  },
  {
    "handle": "umbreon-gx-229-psa-10-3445777",
    "name": "Umbreon GX #229",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 4827.59,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-yosev55i4bfzhqv5-1600-01KZE6577AVWKAQBTPSTF2T194.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-umbreon-gx-229-psa-10-3445777-14ed2dac-01KZE6SHGGA1CNWAVKX7A8H3G5.webp",
    "pokemon_dex": 197,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-197-normal-01KX3XC3E6BN5T8WZWJ95A3WA7.gif"
  },
  {
    "handle": "s-pikachu-7-psa-10-3684133",
    "name": "'s Pikachu #7",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 4329.53,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-sbrlvx4vftkzcjqj-1600-01KZG2XJBDHJ7NFYRVYDKZ7YXX.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-s-pikachu-7-psa-10-3684133-a76055b0-01KZGKKVF7CJMN0JZQ05YMR4RK.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "eevee-gx-188-psa-10-4118654",
    "name": "Eevee GX #188",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 4288.24,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-tdi5fo6sut4he5s2-1600-01KZE60SKTK68E0G3APA9N3QFB.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-eevee-gx-188-psa-10-4118654-464d23da-01KZE6SJNF6DGKATAT2RHWMHW5.webp",
    "pokemon_dex": 133,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-133-normal-01KX3XB549917ZHSWSF2MNMPX0.gif"
  },
  {
    "handle": "mew-ex-347-psa-10-6125392",
    "name": "Mew ex #347",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 4216.75,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-3re7lj6h6aqxecm4-1600-01KZG3NJ7J8PHTFD784XBHP661.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-mew-ex-347-psa-10-6125392-f6283a65-01KZGKKGWW9KKB2SB56RZ1TD0B.webp",
    "pokemon_dex": 151,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-151-normal-01KX3XBDPYKSFC9K7Y4R42WM32.gif"
  },
  {
    "handle": "mew-30-psa-10-3449699",
    "name": "Mew #30",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 2042.72,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-2e868316dd21e6bdcdd3af336bca83e9a331be96ac8f6f0c7dab0f4bba16dcb2-1600-01KZE60Z5DA4AV7WVT6R9F2G0T.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-mew-30-psa-10-3449699-60fa1476-01KZE6T2884TDBT0SS55X8X2KJ.webp",
    "pokemon_dex": 151,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-151-normal-01KX3XBDPYKSFC9K7Y4R42WM32.gif"
  },
  {
    "handle": "charizard-ex-349-psa-10-6125394",
    "name": "Charizard ex #349",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 1961.28,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-rfso7sl5fy6bxlkq-1600-01KZE915WEF7RX2PQEYPJKRBG8.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-charizard-ex-349-psa-10-6125394-745d1d4c-01KZEB0QTJKK7KFG3NK7TXF68C.webp",
    "pokemon_dex": 6,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-6-normal-01KX3X9G679WARSB88WE6NYAMZ.gif"
  },
  {
    "handle": "charizard-5-psa-10-4286114",
    "name": "Charizard #5",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 1938.87,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-tpmsnrar5wmhrbrj-1600-01KZG4AXF3PG8C6A8KVN02VZ9H.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-charizard-5-psa-10-4286114-27634efd-01KZGKK39MZWGBZCEQYA53T38P.webp",
    "pokemon_dex": 6,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-6-normal-01KX3X9G679WARSB88WE6NYAMZ.gif"
  },
  {
    "handle": "lugia-gx-100-psa-10-3468671",
    "name": "Lugia GX #100",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 1887.73,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-83ecf82f190d8c22739584eea3564c30168921b2041816948f866ce74f01ac2d-1600-01KZE6191JWDCKGG0XE02Z7YRE.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-lugia-gx-100-psa-10-3468671-e03cfd90-01KZE6T3T7REJFG27C12PCFJG9.webp",
    "pokemon_dex": 249,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-249-normal-01KX3XCWJ621X0XYEY0C6D65JV.gif"
  },
  {
    "handle": "origin-forme-dialga-vstar-260-psa-10-4447734",
    "name": "Origin Forme Dialga VSTAR #260",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 836.49,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-rv4nwh2jxzf47hwq-1600-01KZG4T9S2CZMCCQEHKQN4ZFHH.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-origin-forme-dialga-vstar-260-psa-10-4447734-e48788e2-01KZGKJV20CTRCHH0M7PF4NSFA.webp",
    "pokemon_dex": 483,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-483-normal-01KX3XGFYARKP3V961M2KEQR1K.gif"
  },
  {
    "handle": "cinccino-ex-117-psa-10-12300918",
    "name": "Cinccino Ex #117",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 518.12,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-vqw7vb5jmz255i7g-1600-01KZNQAB6RKHWG4X7RKPCRHTX0.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-cinccino-ex-117-psa-10-12300918-b470a68d-01KZNZWHH2FYA1YXMJB06FR9YK.webp",
    "pokemon_dex": 573,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-573-normal-01KX3XHWTM0RMBWQ9MF5FFPPV3.gif"
  },
  {
    "handle": "tornadus-158-psa-10-9647436",
    "name": "Tornadus #158",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 490.32,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-so2ltsvrwmn6ybm2-1600-01KZNQ38SAV7J92B1W9B4V94WK.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-tornadus-158-psa-10-9647436-b2ab0be6-01KZP01RC40PFEENRCCJ8GKGK7.webp",
    "pokemon_dex": 641,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-641-normal-01KX3XJX3KZCQ8ED3XTV23279P.gif"
  },
  {
    "handle": "leafeon-vstar-210-psa-10-4447684",
    "name": "Leafeon VSTAR #210",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 487.72,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-y5rwfjvz6yppjkil-1600-01KZG539GKGWV25HZS90T5E5PE.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-leafeon-vstar-210-psa-10-4447684-69ff83de-01KZGKJJCENMFHS95AMVA122X3.webp",
    "pokemon_dex": 470,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-470-normal-01KX3XG99RK0XT5WY7YCNN1B9R.gif"
  },
  {
    "handle": "meowth-ex-100-psa-10-11760288",
    "name": "Meowth ex #100",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 487.38,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-h35x4sloxpdet724-1600-01KZNQDMYNWFWM9RCAYM9JF3NH.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-meowth-ex-100-psa-10-11760288-ea11622c-01KZNZT1JXP989ZCB2P7Q2ZV8G.webp",
    "pokemon_dex": 52,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-52-normal-01KX3XA0Y4MZZ03EZF5239VENW.gif"
  },
  {
    "handle": "pikachu-242-sv-p-psa-10-8844131",
    "name": "Pikachu #242/SV-P",
    "set": "SV-P",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 485.42,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-drxvi7gqkjs5z6fr-1600-01KZGX19V499WEGVWEWT2KER4N.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-pikachu-242-sv-p-psa-10-8844131-4f5df52a-01KZGX8QR1S7E8216SXGBM49FZ.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "solosis-123-psa-10-9683005",
    "name": "Solosis #123",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 357.79,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-tefgj2yuanc7nh2s-1600-01KZNQD6TEVZXZZFH7FGS29652.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-solosis-123-psa-10-9683005-b7565fb6-01KZNZTCMX0WFJ56R6S6TZTXF5.webp",
    "pokemon_dex": 577,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-577-normal-01KX3XHYRHV5HFN9SZ2W2YR4VF.gif"
  },
  {
    "handle": "snivy-87-psa-10-9647330",
    "name": "Snivy #87",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 352.59,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-smsr4fqrg726hcem-1600-01KZNQ74W534K47D2909NZBERM.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-snivy-87-psa-10-9647330-51124486-01KZNZYGE51EJRRCES3W0HR8WA.webp",
    "pokemon_dex": 495,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-495-normal-01KX3XGNP95YYFHPP2T3WTCYMT.gif"
  },
  {
    "handle": "sawk-128-psa-10-9683129",
    "name": "Sawk #128",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 345.68,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-7ev2d2peke4fsvru-1600-01KZNQ3VH3RWZ3XKAHRKJ7EPDZ.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-sawk-128-psa-10-9683129-eca6e3b2-01KZP01BASCWVN9NSCM0QXPAV0.webp",
    "pokemon_dex": 539,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-539-normal-01KX3XHA4MJAQ4P9ZDKKXC9VE1.gif"
  },
  {
    "handle": "mega-kangaskhan-ex-89-psa-10-10085342",
    "name": "Mega Kangaskhan ex #89",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 343.22,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-zcok6i3kdsdc7dcf-1600-01KZNQ7QVNJS8T1XMK0GAHYFSE.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-mega-kangaskhan-ex-89-psa-10-10085342-afc01fbf-01KZNZY6CY39VKCFNS29DWEB6H.webp",
    "pokemon_dex": 115,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-115-normal-01KX3XAXETRWDWRWSDHK71P8X7.gif"
  },
  {
    "handle": "minccino-157-psa-10-9683053",
    "name": "Minccino #157",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 342.49,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-utwawzgkfi2bfdj4-1600-01KZNQ6XXYW3CYDRR3F3AQ4SNX.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-minccino-157-psa-10-9683053-9b4e0a26-01KZNZYNV111QA5Y1N1CKRGGTY.webp",
    "pokemon_dex": 572,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-572-normal-01KX3XHWD1SG5BBQ3C931SVS98.gif"
  },
  {
    "handle": "haxorus-152-psa-10-9683049",
    "name": "Haxorus #152",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 340.33,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-vb5eprqutdmi5ckz-1600-01KZNQ70GWJ1EAD4CDT54WCSEM.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-haxorus-152-psa-10-9683049-68d3540c-01KZNZYKMW8X2QJQXT1YF1DMY4.webp",
    "pokemon_dex": 612,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-612-normal-01KX3XJFWYJ0QQXGY7G6648ZA5.gif"
  },
  {
    "handle": "espeon-master-ball-62-psa-10-7980427",
    "name": "Espeon [Master Ball] #62",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 338.08,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-rvovh36sjmfddbwx-1600-01KZGWXPMTKMMMWM3PKDZMQ5K0.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-espeon-master-ball-62-psa-10-7980427-55919636-01KZGX9MRYEVET5C6CQFP619T0.webp",
    "pokemon_dex": 196,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-196-normal-01KX3XC2YPK4W72H2605GD4HZD.gif"
  },
  {
    "handle": "delphox-v-173-psa-10-4050090",
    "name": "Delphox V #173",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 333.42,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-fd64cf7e032be646737691b77d72d5be5a90505829752a459c0bf0eb2d8ede6c-1600-01KZE65Q8VFGR0YVC3KHYWFEWK.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-delphox-v-173-psa-10-4050090-38719859-01KZE6V34C00HMB2NA6A3VC3RQ.webp",
    "pokemon_dex": 655,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-655-normal-01KX3XK3BCNHPG50EHWWX5BQHQ.gif"
  },
  {
    "handle": "lilligant-92-psa-10-9647453",
    "name": "Lilligant #92",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 330.97,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-dw4ghydzqqyxvzmm-1600-01KZNQ6H881BVA2FMSKYE47CXQ.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-lilligant-92-psa-10-9647453-c7de92d6-01KZNZZ0CMPYPKPHB5EN987ZS2.webp",
    "pokemon_dex": 549,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-549-normal-01KX3XHEAG4VXY0QBWCRTN9EZJ.gif"
  },
  {
    "handle": "cubchoo-113-psa-10-9682995",
    "name": "Cubchoo #113",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 329.2,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-6uqio2shhnfyn6y6-1600-01KZNQ6VAHP2F8SDXH2J8JTMX1.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-cubchoo-113-psa-10-9682995-2ee0975d-01KZNZYRF4TSR3S62XZ91JVKSH.webp",
    "pokemon_dex": 613,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-613-normal-01KX3XJGCZWKEEPPHF2KAHQHC1.gif"
  },
  {
    "handle": "pikachu-ex-1st-edition-94-psa-10-3506822",
    "name": "Pikachu EX [1st Edition] #94",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 41231.01,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-hfpdknookranpgr5-1600-01KZPBYY9K9J31D5EJGC761Q0W.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-pikachu-ex-1st-edition-94-psa-10-3506822-beb89cd6-01KZPCAJ2THG98F8HZR2T14DTA.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "gengar-ex-1st-edition-90-psa-10-3507567",
    "name": "Gengar EX [1st Edition] #90",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 38667.32,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-jh5b7arg55n2mxys-1600-01KZPBZ9YST7NA9TY5GCVRMWPZ.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-gengar-ex-1st-edition-90-psa-10-3507567-4a143160-01KZPCAB4JEYB6K5Y20Z102CCG.webp",
    "pokemon_dex": 94,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-94-normal-01KX3XAN9DSVW9T3E0KD93WKG4.gif"
  },
  {
    "handle": "latias-latios-gx-105-psa-10-3468793",
    "name": "Latias & Latios GX #105",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 37264.32,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-vlfrrqmndk7cl555-1600-01KZG46J46NN7HKB36SAK2VJ90.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-latias-latios-gx-105-psa-10-3468793-cd15a598-01KZGKK9DQSER76NX9TXHQS5V5.webp",
    "pokemon_dex": 380,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-380-normal-01KX3XEW6E5Y4CPRFVNS9R6Z18.gif"
  },
  {
    "handle": "ooyama-s-pikachu-series-iii-25-psa-10-3473852",
    "name": "Ooyama's Pikachu [Series III] #25",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 36230.43,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-49dbf2a0cabb23fb293dde3ed7536fdb956f959e4800dbcb7a24f248acb19a5f-1600-01KZE643SPKHK5S5RB55FSNAHW.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-ooyama-s-pikachu-series-iii-25-psa-10-3473852-ec63a31d-01KZE6RJB8SZSHMRCX4M82J56S.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "mew-ex-1st-edition-24-psa-10-4723460",
    "name": "Mew EX [1st Edition] #24",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 34925.44,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-32pylc6bhqfuagmu-1600-01KZE64G2GRP6QQKVPSN12SEFB.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-mew-ex-1st-edition-24-psa-10-4723460-0321945b-01KZE6RKKYNNP43WWNWTXWAF65.webp",
    "pokemon_dex": 151,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-151-normal-01KX3XBDPYKSFC9K7Y4R42WM32.gif"
  },
  {
    "handle": "pikachu-ex-764-psa-10-11463099",
    "name": "Pikachu ex #764",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 11954.2,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-e63ewzz7iycjbafi-1600-01KZG3P41SRJTVSR4EA264RVHP.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-pikachu-ex-764-psa-10-11463099-3830059b-01KZGKKEYC0NRWV3GY8PPAQBWE.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "mega-gengar-ex-284-psa-10-11816195",
    "name": "Mega Gengar ex #284",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 10909.62,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-tgpr6qzpnxydngtc-1600-01KZPBZ81WWM5Y2H6BT4F22S26.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-mega-gengar-ex-284-psa-10-11816195-04b652d2-01KZPCAC7KQSTC9R23A61XYK0K.webp",
    "pokemon_dex": 94,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-94-normal-01KX3XAN9DSVW9T3E0KD93WKG4.gif"
  },
  {
    "handle": "gyarados-ex-89-psa-10-3462587",
    "name": "Gyarados EX #89",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 10755.56,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-q6gp5hylfl2ltmw4-1600-01KZPBZ6MYT49D9JMR0TK13EBX.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-gyarados-ex-89-psa-10-3462587-d29c9f9b-01KZPCAD4R8EXM74F4AA7NWKJF.webp",
    "pokemon_dex": 130,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-130-normal-01KX3XB3SYKS1MDGPY9792KWFN.gif"
  },
  {
    "handle": "gardevoir-sylveon-gx-61-psa-10-3469236",
    "name": "Gardevoir & Sylveon GX #61",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 9991.45,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-1f078ab58a41adadc302fa8c6ef5efc707de8199d6e044097321a5b5641dcb8e-1600-01KZE63P6W24K216PZZHMGG0KW.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-gardevoir-sylveon-gx-61-psa-10-3469236-894bf6c5-01KZE6S8252DAM9NQD40GWZZ8Z.webp",
    "pokemon_dex": 700,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-700-normal-01KX3XM6VKJG9D693P3KPABTY9.gif"
  },
  {
    "handle": "charizard-1-psa-10-3684127",
    "name": "Charizard #1",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 3867.64,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-xk6nefam4wnwzeyk-1600-01KZE60R7MB2QTV5QARACHJWAZ.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-charizard-1-psa-10-3684127-f0300948-01KZE6SMPYZDS85XHRZKNPQ8EM.webp",
    "pokemon_dex": 6,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-6-normal-01KX3X9G679WARSB88WE6NYAMZ.gif"
  },
  {
    "handle": "roaring-moon-ex-162-psa-10-8244605",
    "name": "Roaring Moon ex #162",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 3677.35,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-msgsjjskgxgnpn2b-1600-01KZE6251T4KZCXPGT5M66F3P4.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-roaring-moon-ex-162-psa-10-8244605-e1ebc578-01KZE6SNXJTFV90PF39GVJQ9X8.webp",
    "pokemon_dex": 1005,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-1005-normal-01KX3XSGZDA053H1341CWWFDRS.gif"
  },
  {
    "handle": "pikachu-tg05-psa-10-4080757",
    "name": "Pikachu #TG05",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 3646.66,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-0a3b90cc5a6c3be5fe9091d6ea1cd572ebd5765af32dee917d12b19d26d3e2f6-1600-01KZE606F2Z45T9SBNRGKZZDT3.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-pikachu-tg05-psa-10-4080757-a4453a12-01KZE6SPZ3HXCFWEY2B5VAV0J0.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "rayquaza-gx-177a-psa-10-2390421",
    "name": "Rayquaza GX #177a",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 3590.56,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-ff0df623e64c3fd2d4a28ad3e3845d5e16760e2b38d0e6bed2c84cf817c3984d-1600-01KZG3XGVAXR1HTDARAYSWAF4P.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-rayquaza-gx-177a-psa-10-2390421-cc34c783-01KZGKKBN06XVH5634DYZDG8Z5.webp",
    "pokemon_dex": 384,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-384-normal-01KX3XEY4VN4C59338HD2H5X2Q.gif"
  },
  {
    "handle": "mega-lucario-ex-92-psa-10-10117206",
    "name": "Mega Lucario Ex #92",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 3417.78,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-qq6eiiefftgndxtd-1600-01KZNQ85AW7P962E85ASYP1H17.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-mega-lucario-ex-92-psa-10-10117206-5e4c45c9-01KZNZXXEQEEYJKP9SZCP96482.webp",
    "pokemon_dex": 448,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-448-normal-01KX3XFYAM4RRVEART6BE5GRRG.gif"
  },
  {
    "handle": "mega-gardevoir-ex-92-psa-10-10117212",
    "name": "Mega Gardevoir Ex #92",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 3383.26,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-ju2e7t6r3k6kfnfa-1600-01KZNQ7S0WGCS6D8NKHFV0FV3H.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-mega-gardevoir-ex-92-psa-10-10117212-a107a6fe-01KZNZY56T9X2851WJSRPWN6YZ.webp",
    "pokemon_dex": 282,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-282-normal-01KX3XDD5619DC58BM5YY3RDEY.gif"
  },
  {
    "handle": "greninja-ex-90-psa-10-6526274",
    "name": "Greninja ex #90",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 1745.54,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-xfcdwch653z74bo6-1600-01KZG3N687DK0AYTPJ18QV61F4.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-greninja-ex-90-psa-10-6526274-c959ee9c-01KZGKKP42T7F3JFXWTXQREDVW.webp",
    "pokemon_dex": 658,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-658-normal-01KX3XK4RMA2JQFBC3ABGQPYV0.gif"
  },
  {
    "handle": "giratina-vstar-261-psa-10-4447735",
    "name": "Giratina VSTAR #261",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 1716.12,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-3tuq4ui63leuod5k-1600-01KZG4T6AY1PY1W6DMR7BRF006.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-giratina-vstar-261-psa-10-4447735-c0cae2e4-01KZGKJWVMB5PRB02DANC0TB01.webp",
    "pokemon_dex": 487,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-487-normal-01KX3XGHW9BK42PEX6H11X59RC.gif"
  },
  {
    "handle": "pikachu-vmax-tg17-psa-10-4080769",
    "name": "Pikachu VMAX #TG17",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 1577.95,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-49f2f1a7f3e0b56b4e774eea792cfd4a41c97f12a2bc417731ddf3c995e12e46-1600-01KZE61VADQFFK19WT7KN2FA3W.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-pikachu-vmax-tg17-psa-10-4080769-80a221ca-01KZE6T5R3RDMXJ972GC5T4DWX.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "reshiram-charizard-gx-20-psa-10-963176",
    "name": "Reshiram & Charizard GX #20",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 1569.02,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-c0f1bfe3d1f1682e60fbc5c8e37cfe105c998ae5f0586ef34be6cee35d6bc4b9-1600-01KZE65S8B729BJ81NS3P62HXD.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-reshiram-charizard-gx-20-psa-10-963176-e8a9ec49-01KZE6T8YS53ZYABBQ26JEFQ27.webp",
    "pokemon_dex": 6,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-6-normal-01KX3X9G679WARSB88WE6NYAMZ.gif"
  },
  {
    "handle": "hiroshima-s-pikachu-261-sv-p-psa-10-10605024",
    "name": "Hiroshima's Pikachu #261/SV-P",
    "set": "SV-P",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 1569.02,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-b3bvmycsljniepgt-1600-01KZPAGE04N87JCR16BT8W4JXP.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-hiroshima-s-pikachu-261-sv-p-psa-10-10605024-9b6e94fc-01KZPCAM6EHC7B7PDAX0KECVE8.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "sylveon-ex-212-psa-10-7980830",
    "name": "Sylveon Ex #212",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 1010.94,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-qutc3u4wyr2ed3nv-1600-01KZGWXSZ5AXN2B6GPDVGCTPN7.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-sylveon-ex-212-psa-10-7980830-cc0756d3-01KZGX9J5MTP7KFEB763G8C26X.webp",
    "pokemon_dex": 700,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-700-normal-01KX3XM6VKJG9D693P3KPABTY9.gif"
  },
  {
    "handle": "lillie-s-clefairy-ex-126-psa-10-8437204",
    "name": "Lillie's Clefairy ex #126",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 980.64,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-pvnfbuenm2kckpt3-1600-01KZG4MGTGT5F4KGZGCV2DWDCR.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-lillie-s-clefairy-ex-126-psa-10-8437204-8185a9df-01KZGKK1393SQBFF4XVXHTZG43.webp",
    "pokemon_dex": 35,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-35-normal-01KX3X9V0JVSCMXGT71Y265HBJ.gif"
  },
  {
    "handle": "pikachu-173-psa-10-5326214",
    "name": "Pikachu #173",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 727.14,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-cext36ozjte5xexz-1600-01KZGWYF3M9Q11C4KYGHJWW9NB.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-pikachu-173-psa-10-5326214-c391275b-01KZGX958T92GN7M76BZQCR5ZR.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "palkia-ex-7-psa-10-5253065",
    "name": "Palkia EX #7",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 681.54,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-akz6hbnjvm4cqyc5-1600-01KZE62Z9TYW74JCFQS9QMMX8Q.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-palkia-ex-7-psa-10-5253065-85ce32ff-01KZE6TN8V9QHC9JCJYZ7WT05J.webp",
    "pokemon_dex": 484,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-484-normal-01KX3XGGE704R2MX2QM2EVNWRN.gif"
  },
  {
    "handle": "leafeon-ex-200-psa-10-8054193",
    "name": "Leafeon Ex #200",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 673.99,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-nwn3omsdpm7wkpcv-1600-01KZE62C7X31GAJMW0K0ND1VV4.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-leafeon-ex-200-psa-10-8054193-bb8e0836-01KZE6TKJKMA5M7A2NG96W3TJQ.webp",
    "pokemon_dex": 470,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-470-normal-01KX3XG99RK0XT5WY7YCNN1B9R.gif"
  },
  {
    "handle": "glaceon-ex-206-psa-10-7980823",
    "name": "Glaceon Ex #206",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 665.61,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-i766k2yelvobzz6v-1600-01KZGYWREZTC7C2YSQN69MYG6C.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-glaceon-ex-206-psa-10-7980823-50d8d8e9-01KZGYX7F01D1ZPT9GH7NHAD3Q.webp",
    "pokemon_dex": 471,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-471-normal-01KX3XG9SWYR4ZCX45ZKX2CSJK.gif"
  },
  {
    "handle": "team-rocket-s-nidoking-ex-126-psa-10-9090615",
    "name": "Team Rocket's Nidoking ex #126",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 632.76,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-hvv6zfllkrltwlyv-1600-01KZE6315HCD9PMHXPXVKNFRTX.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-team-rocket-s-nidoking-ex-126-psa-10-9090615-b22bee80-01KZE6TQMDF1ZRAZ7BEKSACVEK.webp",
    "pokemon_dex": 34,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-34-normal-01KX3X9TJ7XPY0A6AC9E0CWDBV.gif"
  },
  {
    "handle": "poncho-wearing-pikachu-charizard-208-xy-p-psa-10-4856869",
    "name": "Poncho-Wearing Pikachu Charizard #208/XY-P",
    "set": "XY-P",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 85801.1,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-c39f90a8a30698f6e4b4a0da19c4c4472907a17bec6ff1e370bc693e31ebbd2a-1600-01KZPBZFW2N1DYYW60GC0ADXRQ.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-poncho-wearing-pikachu-charizard-208-xy-p-psa-10-4856869-7951034a-01KZPCA5CW8WHP6YPJA6FVJ0G3.webp",
    "pokemon_dex": 6,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-6-normal-01KX3X9G679WARSB88WE6NYAMZ.gif"
  },
  {
    "handle": "poncho-wearing-pikachu-231-xy-p-psa-10-2812854",
    "name": "Poncho-Wearing Pikachu #231/XY-P",
    "set": "XY-P",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 85070.52,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-87a17da914156f967b710ce2ae8c8e50e7776054df68ba48828a351dbb9b28ac-1600-01KZG4MESWM61ME4X0YVZBFD81.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-poncho-wearing-pikachu-231-xy-p-psa-10-2812854-001e2624-01KZGKK1T9DCHQ2N8HE73T310V.webp",
    "pokemon_dex": 384,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-384-normal-01KX3XEY4VN4C59338HD2H5X2Q.gif"
  },
  {
    "handle": "luigi-pikachu-296-xy-p-psa-10-5047630",
    "name": "Luigi Pikachu #296/XY-P",
    "set": "XY-P",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 78279.1,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-e68ebe63748bb02dfd0f4e70777547b7d99c1857b77014aed4c369d226942da8-1600-01KZPBZF39N2CRFTTK8BVYAZHV.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-luigi-pikachu-296-xy-p-psa-10-5047630-527e99da-01KZPCA66T4HDCXC50YHQ32DKF.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "latias-latios-gx-170-psa-10-962968",
    "name": "Latias & Latios GX #170",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 77960.88,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-2103b247d22ccbb521606384496b563d132579ac520bd6f3f96d3ea66d7f84ab-1600-01KZG46HC31PWE2TS9SBKP2RK3.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-latias-latios-gx-170-psa-10-962968-38d6e033-01KZGKKA8WC4FTSYCQR9YMH8KX.webp",
    "pokemon_dex": 380,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-380-normal-01KX3XEW6E5Y4CPRFVNS9R6Z18.gif"
  },
  {
    "handle": "umbreon-68-psa-10-3438471",
    "name": "Umbreon #68",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 22570.46,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-yxkdus5i6mphwvys-1600-01KZE647V8FA9Z00BQVHTD3GN5.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-umbreon-68-psa-10-3438471-848e45e8-01KZE6RVMPJ1RRS9Z522QQ8QB8.webp",
    "pokemon_dex": 197,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-197-normal-01KX3XC3E6BN5T8WZWJ95A3WA7.gif"
  },
  {
    "handle": "easter-pikachu-55-sm-p-psa-10-5769157",
    "name": "Easter Pikachu #55/SM-P",
    "set": "SM-P",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 18623.87,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-6fd934f6d4d6a23859c3af7fd08a609d5be2a5af53b37d1e4f2d14da7355bbf2-1600-01KZE61SRPGNFWBD92T2SS2MM6.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-easter-pikachu-55-sm-p-psa-10-5769157-4b445eec-01KZE6RT75QGSCJ4VHTG352Y65.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "team-magma-s-groudon-ex-15-psa-10-3445235",
    "name": "Team Magma's Groudon EX #15",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 17970.23,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-corrxethgmtq36mqhamk-1600-01KZPBZJPPXC9E45A5K355SMY3.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-team-magma-s-groudon-ex-15-psa-10-3445235-f683b87f-01KZPCA3CZKKVF9SZ1GYS5BJB0.webp",
    "pokemon_dex": 383,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-383-normal-01KX3XEXFT9WCH2MY4EA9ANX8R.gif"
  },
  {
    "handle": "giratina-v-186-psa-10-4050103",
    "name": "Giratina V #186",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 16861.42,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-e622ba2e940cc994306094e71915abe8dbe53a5ae6371eb2f2e969e2ba1b6e29-1600-01KZE61ND6EEH29T27EM5Q7G3M.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-giratina-v-186-psa-10-4050103-3110c408-01KZE6RWTAH5B5QQ7T29TD4DX6.webp",
    "pokemon_dex": 487,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-487-normal-01KX3XGHW9BK42PEX6H11X59RC.gif"
  },
  {
    "handle": "gengar-mimikyu-gx-103-psa-10-3468791",
    "name": "Gengar & Mimikyu GX #103",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 16487.01,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-1e9fc7da24a051c35240577e5050a1d71b324f9398d0c013db8ae40e07635bfe-1600-01KZG3WGH5MRAANG80Q8Z95SR9.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-gengar-mimikyu-gx-103-psa-10-3468791-dd83c270-01KZGKKDG8RPJWSSHPZ0DWQ7CA.webp",
    "pokemon_dex": 778,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-778-normal-01KX3XNRFEMJV3D7PS6MBN6GMH.gif"
  },
  {
    "handle": "reshiram-1st-edition-22-psa-10-4723458",
    "name": "Reshiram [1st Edition] #22",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 16460.04,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-iympm754pglzim5s-1600-01KZE622AQ8G2NGYWYT5EVMZSY.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-reshiram-1st-edition-22-psa-10-4723458-e56a47be-01KZE6S2FB63ECMEJ6VZQA62FC.webp",
    "pokemon_dex": 643,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-643-normal-01KX3XJXY9F7BBW7MMC4R0RAB7.gif"
  },
  {
    "handle": "rayquaza-v-76-psa-10-3472904",
    "name": "Rayquaza V #76",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 7845.07,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-o2o7ymgjdfzvmzfv-1600-01KZG3NG67VPE6VCW3H44D611P.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-rayquaza-v-76-psa-10-3472904-f4ee9d8a-01KZG5JREM2WB8FCQXTH1K3GT2.webp",
    "pokemon_dex": 384,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-384-normal-01KX3XEY4VN4C59338HD2H5X2Q.gif"
  },
  {
    "handle": "charizard-vstar-swsh262-psa-10-4246447",
    "name": "Charizard VStar #SWSH262",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 7394.03,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-f9763f876795ae797afdfe97628cee8db120e2109a4329568d74ce6e1d5d066a-1600-01KZE65MS5JMHT6G8PHKVVVHQM.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-charizard-vstar-swsh262-psa-10-4246447-28d0ba1b-01KZE6S98BA2ZRJGC844Q1W2WG.webp",
    "pokemon_dex": 6,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-6-normal-01KX3X9G679WARSB88WE6NYAMZ.gif"
  },
  {
    "handle": "darkrai-ex-72-psa-10-3460952",
    "name": "Darkrai EX #72",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 7354.8,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-v2dlypn75ovovwmx-1600-01KZG3BY7JP6XAMXSGC4RJA2W1.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-darkrai-ex-72-psa-10-3460952-4556518f-01KZGKKSJJPP8F2QM7BNWVMZ9C.webp",
    "pokemon_dex": 491,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-491-normal-01KX3XGKQY4YN4G9ZWTV5X5P87.gif"
  },
  {
    "handle": "charizard-gx-sv49-psa-10-964133",
    "name": "Charizard GX #SV49",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 7227.71,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-556d3eab00d5ea76807dad43a619f39614dcb774d5e4334f97567526fed14741-1600-01KZE65ZJJW8B1MVK6379MWK39.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-charizard-gx-sv49-psa-10-964133-8279b464-01KZE6SB1WT4TJNZQXDWPFX6BT.webp",
    "pokemon_dex": 6,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-6-normal-01KX3X9G679WARSB88WE6NYAMZ.gif"
  },
  {
    "handle": "pikachu-holo-1st-edition-7-psa-10-4723443",
    "name": "Pikachu [Holo 1st Edition] #7",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 7004.47,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-l2jjn64aefou7tqw-1600-01KZG4MP8RQV84BED849F5XS60.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-pikachu-holo-1st-edition-7-psa-10-4723443-de938a46-01KZGKJZ2HD67TTENMV3X4XSJG.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "rayquaza-vmax-tg20-psa-10-4277108",
    "name": "Rayquaza VMAX #TG20",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 2120.58,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-7uqk7vfjh7x4zx55-1600-01KZPACNSCKEYDF2GEJX6MBME8.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-rayquaza-vmax-tg20-psa-10-4277108-ce9778b3-01KZPCAQH6W7V6R6MVFF9HZVG3.webp",
    "pokemon_dex": 384,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-384-normal-01KX3XEY4VN4C59338HD2H5X2Q.gif"
  },
  {
    "handle": "pikachu-ex-234-psa-10-11302600",
    "name": "Pikachu ex #234",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 2086.31,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-aydmckfpcaq7arxu-1600-01KZE8H5Z0XBQXDY0MHV0BDM84.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-pikachu-ex-234-psa-10-11302600-e2341da2-01KZEB0VJGTREMRQEM4WN75DQB.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "mew-ex-205-psa-10-5809586",
    "name": "Mew ex #205",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 1483.22,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-x3eikmhww6ph7tzt-1600-01KZE63BZN8TMYDYETYDD3Y1CT.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-mew-ex-205-psa-10-5809586-fcb4bec7-01KZE6T6TAVRDPCDFH0528G0Q5.webp",
    "pokemon_dex": 151,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-151-normal-01KX3XBDPYKSFC9K7Y4R42WM32.gif"
  },
  {
    "handle": "pikachu-v-104-psa-10-3472139",
    "name": "Pikachu V #104",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 1475.86,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-nz4vt4ce6xfrsmea-1600-01KZGWYHW3322A9ATXNZQDM9KV.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-pikachu-v-104-psa-10-3472139-6eb59caf-01KZGX93NGKF2FNC7BEKAKYNXD.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "magikarp-80-psa-10-4947437",
    "name": "Magikarp #80",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 1421.93,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-viuq7dfcjhc56l35-1600-01KZG4MK0CND3HT6PE5CSY5A2K.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-magikarp-80-psa-10-4947437-dcb783a2-01KZGKK039BC9S2VJ749BV29W3.webp",
    "pokemon_dex": 129,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-129-normal-01KX3XB3AVBFPMY57Y58613VM6.gif"
  },
  {
    "handle": "detective-pikachu-14-psa-10-4034126",
    "name": "Detective Pikachu #14",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 1397.31,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-e5e89dd7996cb81b2d7ff7fe4c533cbf9fd5bd32720b1c4699fa5357c064bf55-1600-01KZE652SMBVMW85SYKVEA4NH3.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-detective-pikachu-14-psa-10-4034126-2f027a27-01KZE6TB0TYA5HDZS20KY3SS83.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "mega-greninja-ex-114-psa-10-12271092",
    "name": "Mega Greninja Ex #114",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 1378.14,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-yd6auwcicegqek77-1600-01KZG3N7QMJE5KSNSB9NB1TKNW.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-mega-greninja-ex-114-psa-10-12271092-cca3346e-01KZGKKN4M8XMNZVQD3AMA929E.webp",
    "pokemon_dex": 658,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-658-normal-01KX3XK4RMA2JQFBC3ABGQPYV0.gif"
  },
  {
    "handle": "charizard-ex-105-psa-10-850072",
    "name": "Charizard EX #105",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 187001.92,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-aa57ce31cb38beb62abb81a460e73c98f9e88da73611613398164d0d45df0219-1600-01KZPFVR9DYV9YMBMXG9KDWFHP.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-charizard-ex-105-psa-10-850072-63660179-01KZPFXVPEZQXCQGJ8WV3QK32S.webp",
    "pokemon_dex": 6,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-6-normal-01KX3X9G679WARSB88WE6NYAMZ.gif"
  },
  {
    "handle": "pikachu-gold-star-1-psa-10-5491689",
    "name": "Pikachu [Gold Star] #1",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 181418.4,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-8c90f9bd981a43859f84d8834f9c1bbee8ceb646943f78cf0cd02824a974ac1d-1600-01KZPFVSDMADBK97GCS18ZACSM.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-pikachu-gold-star-1-psa-10-5491689-3af1446c-01KZPFXTMCTS46GE898XMYDGNV.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "charizard-gold-star-1st-edition-52-psa-10-9866070",
    "name": "Charizard [Gold Star 1st Edition] #52",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 171234.45,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-e5xq3g6ou4zeoyrm-1600-01KZPFVV3Q9PNB3C5CCCJ5HMZR.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-charizard-gold-star-1st-edition-52-psa-10-9866070-bd5e40dc-01KZPFXSPCXE4FZMAJYYFBBERE.webp",
    "pokemon_dex": 6,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-6-normal-01KX3X9G679WARSB88WE6NYAMZ.gif"
  },
  {
    "handle": "pikachu-20th-anniversary-festa-279-xy-p-psa-10-2740820",
    "name": "Pikachu 20th Anniversary Festa #279/XY-P",
    "set": "XY-P",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 153834.32,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-wvulrwkgfps34roz-1600-01KZPBZH8NG66Z2YWGRPVB50RM.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-pikachu-20th-anniversary-festa-279-xy-p-psa-10-2740820-3cac8e57-01KZPCA4K3267Q1C2RJ9YGFQB5.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "mario-pikachu-294-xy-p-psa-10-4956613",
    "name": "Mario Pikachu #294/XY-P",
    "set": "XY-P",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 147096,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-r6adn2pfxnwkbvt3-1600-01KZGWY5CBQMW0G7T5DC3KKGHJ.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-mario-pikachu-294-xy-p-psa-10-4956613-cedbed13-01KZGX9A5M7HJ8XNX3R0ND9CVD.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "luigi-pikachu-295-xy-p-psa-10-5058483",
    "name": "Luigi Pikachu #295/XY-P",
    "set": "XY-P",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 34317.5,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-bf1815f305d71efd06400c64c4317ae7e9a38c06ff5aedd253396a18b36ad3d7-1600-01KZPBZE4VY8V7252A0DA9HX5Z.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-luigi-pikachu-295-xy-p-psa-10-5058483-6954c6bf-01KZPCA6XVWSTNWH9EHS0KDV5A.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "rayquaza-vmax-83-psa-10-3472911",
    "name": "Rayquaza VMAX #83",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 33111.95,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-ofbt6h4m3eonw64c-1600-01KZPACQGFZ53P8CBCGFR5JQNE.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-rayquaza-vmax-83-psa-10-3472911-cbd66b5a-01KZPCAPDH33N061XQEX6X153Y.webp",
    "pokemon_dex": 384,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-384-normal-01KX3XEY4VN4C59338HD2H5X2Q.gif"
  },
  {
    "handle": "pikachu-ex-xy84-psa-10-844750",
    "name": "Pikachu EX #XY84",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 32851.44,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-d9ee52ac64c0008a300928133726817bdd3bc7784da499769065ec66568ebf75-1600-01KZE64BM5NM5JMCBW2HQX1BK5.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-pikachu-ex-xy84-psa-10-844750-4b0d01d1-01KZE6RNNAY7RTX6A4E9SC0B72.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "flareon-ex-7-psa-10-4557547",
    "name": "Flareon EX #7",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 16159.62,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-4kiuwnr2xirzu7tf-1600-01KZGWY1YDW7QS8CDG16Z8WJM1.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-flareon-ex-7-psa-10-4557547-a5905e04-01KZGX9BXPNWFDNJN0QECZTPXJ.webp",
    "pokemon_dex": 136,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-136-normal-01KX3XB6F8RPTF2T0RD6X0MERR.gif"
  },
  {
    "handle": "sylveon-ex-26-psa-10-4557566",
    "name": "Sylveon EX #26",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 15935.4,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-f62db1f8b4161437132ae8cf2e011092f5c371c618d47952f6970a2fc7d96168-1600-01KZPBZCD2VP9RVDW3M18DET9G.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-sylveon-ex-26-psa-10-4557566-fb4df29f-01KZPCA8RR159NSEN8RRSH2JNF.webp",
    "pokemon_dex": 700,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-700-normal-01KX3XM6VKJG9D693P3KPABTY9.gif"
  },
  {
    "handle": "mewtwo-mew-gx-98-psa-10-3470024",
    "name": "Mewtwo & Mew GX #98",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 15152.11,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-7lap7joji6mymxco-1600-01KZG52CNCG6PGQJ8DF575VPQ0.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-mewtwo-mew-gx-98-psa-10-3470024-45ff7306-01KZGKJK711HD1GAVZCACRZYKC.webp",
    "pokemon_dex": 151,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-151-normal-01KX3XBDPYKSFC9K7Y4R42WM32.gif"
  },
  {
    "handle": "mewtwo-3-psa-10-643534",
    "name": "Mewtwo #3",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 6762.74,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-h5dop3b25mpczvyt-1600-01KZE65NKGN674JYTMBEKK0J3R.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-mewtwo-3-psa-10-643534-d957e29f-01KZE6SCVQ3S5BYD368170PV2P.webp",
    "pokemon_dex": 150,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-150-normal-01KX3XBD78G0BCF0Q933SWTJ18.gif"
  },
  {
    "handle": "pretend-comedian-pikachu-407-sm-p-psa-10-4225263",
    "name": "Pretend Comedian Pikachu #407/SM-P",
    "set": "SM-P",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 4888.93,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-iydsh52ydifo3til-1600-01KZGWYGJ4FHN5VP0R3V767MFQ.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-pretend-comedian-pikachu-407-sm-p-psa-10-4225263-ff20efc3-01KZGX94F2ERXMZ4W12QT5JREJ.webp",
    "pokemon_dex": 25,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-25-normal-01KX3X9PZ546XZK89QX360EANW.gif"
  },
  {
    "handle": "mewtwo-vstar-gg44-psa-10-4637100",
    "name": "Mewtwo VSTAR #GG44",
    "set": "Prod Snapshot",
    "grader": "PSA",
    "grade": "10",
    "display_myr": 2929.66,
    "image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pc-77076817ef37dde7fd186921d3611c6ad07a6796b9c0667f3096dfd8b9f27a7c-1600-01KZE62HEMAQA0G94BZHNTKXV1.webp",
    "slab_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/slab-mewtwo-vstar-gg44-psa-10-4637100-87a52035-01KZE6SXSJVDGG1SBR3P9VMG30.webp",
    "pokemon_dex": 150,
    "sprite_image": "https://polycards-media.sgp1.cdn.digitaloceanspaces.com/pixel-pokemon-150-normal-01KX3XBD78G0BCF0Q933SWTJ18.gif"
  }
];

export const PROD_PACKS: ProdCatalogPack[] = [
  {
    "slug": "bronze-pack",
    "title": "Bronze Pack",
    "price": 300,
    "buyback_percent": 90,
    "image": "/images/polycards/bronze-pack.webp",
    "display_image": "/images/polycards/bronze-factory.webp",
    "rank": 0,
    "cards": [
      {
        "handle": "rowlet-290-sm-p-psa-10-4683337",
        "rarity": "Immortal"
      },
      {
        "handle": "hoopa-155-xy-p-psa-10-4188987",
        "rarity": "Immortal"
      },
      {
        "handle": "reshiram-ex-166-psa-10-10026819",
        "rarity": "Legendary"
      },
      {
        "handle": "pikachu-205-psa-10-4447679",
        "rarity": "Legendary"
      },
      {
        "handle": "detective-pikachu-98-sv-p-psa-10-5873374",
        "rarity": "Legendary"
      },
      {
        "handle": "team-rocket-s-moltres-ex-124-psa-10-9090613",
        "rarity": "Mythical"
      },
      {
        "handle": "glaceon-vstar-gg40-psa-10-4637096",
        "rarity": "Mythical"
      },
      {
        "handle": "pikachu-zekrom-gx-41-psa-10-4118507",
        "rarity": "Mythical"
      },
      {
        "handle": "mega-latias-ex-88-psa-10-10117332",
        "rarity": "Rare"
      },
      {
        "handle": "eevee-ex-224-psa-10-8054200",
        "rarity": "Rare"
      },
      {
        "handle": "keldeo-ex-169-psa-10-9692268",
        "rarity": "Rare"
      },
      {
        "handle": "mega-clefable-ex-112-psa-10-11760300",
        "rarity": "Rare"
      },
      {
        "handle": "sawsbuck-92-psa-10-9683082",
        "rarity": "Uncommon"
      },
      {
        "handle": "lillipup-153-psa-10-9688434",
        "rarity": "Uncommon"
      },
      {
        "handle": "drampa-83-psa-10-6281530",
        "rarity": "Uncommon"
      },
      {
        "handle": "sprigatito-75-psa-10-4947432",
        "rarity": "Uncommon"
      },
      {
        "handle": "musharna-122-psa-10-9683004",
        "rarity": "Uncommon"
      },
      {
        "handle": "darmanitan-99-psa-10-9681337",
        "rarity": "Uncommon"
      },
      {
        "handle": "darumaka-98-psa-10-9681336",
        "rarity": "Uncommon"
      },
      {
        "handle": "amoonguss-96-psa-10-9681335",
        "rarity": "Uncommon"
      },
      {
        "handle": "pikachu-291-sv-p-psa-10-11750071",
        "rarity": "Uncommon"
      },
      {
        "handle": "vanillite-108-psa-10-9683091",
        "rarity": "Uncommon"
      },
      {
        "handle": "serperior-ex-167-psa-10-9647339",
        "rarity": "Uncommon"
      },
      {
        "handle": "zebstrika-112-psa-10-9683095",
        "rarity": "Common"
      },
      {
        "handle": "zacian-87-psa-10-10602360",
        "rarity": "Common"
      },
      {
        "handle": "spearow-74-psa-10-10117514",
        "rarity": "Common"
      },
      {
        "handle": "klawf-88-psa-10-4708204",
        "rarity": "Common"
      },
      {
        "handle": "decidueye-ex-12-psa-10-11748931",
        "rarity": "Common"
      },
      {
        "handle": "munna-121-psa-10-9683003",
        "rarity": "Common"
      },
      {
        "handle": "mega-absol-ex-79-psa-10-10117520",
        "rarity": "Common"
      }
    ]
  },
  {
    "slug": "silver-pack",
    "title": "Silver Pack",
    "price": 600,
    "buyback_percent": 90,
    "image": "/images/polycards/silver-pack.webp",
    "display_image": "/images/polycards/silver-factory.webp",
    "rank": 1,
    "cards": [
      {
        "handle": "pikachu-227-s-p-psa-10-4199649",
        "rarity": "Immortal"
      },
      {
        "handle": "mewtwo-1st-edition-118-psa-10-3507074",
        "rarity": "Immortal"
      },
      {
        "handle": "umbreon-vmax-215-psa-10-2513024",
        "rarity": "Immortal"
      },
      {
        "handle": "umbreon-gx-229-psa-10-3445777",
        "rarity": "Legendary"
      },
      {
        "handle": "s-pikachu-7-psa-10-3684133",
        "rarity": "Legendary"
      },
      {
        "handle": "eevee-gx-188-psa-10-4118654",
        "rarity": "Legendary"
      },
      {
        "handle": "mew-ex-347-psa-10-6125392",
        "rarity": "Legendary"
      },
      {
        "handle": "mew-30-psa-10-3449699",
        "rarity": "Mythical"
      },
      {
        "handle": "charizard-ex-349-psa-10-6125394",
        "rarity": "Mythical"
      },
      {
        "handle": "charizard-5-psa-10-4286114",
        "rarity": "Mythical"
      },
      {
        "handle": "lugia-gx-100-psa-10-3468671",
        "rarity": "Mythical"
      },
      {
        "handle": "team-rocket-s-moltres-ex-124-psa-10-9090613",
        "rarity": "Rare"
      },
      {
        "handle": "pikachu-zekrom-gx-41-psa-10-4118507",
        "rarity": "Rare"
      },
      {
        "handle": "origin-forme-dialga-vstar-260-psa-10-4447734",
        "rarity": "Rare"
      },
      {
        "handle": "cinccino-ex-117-psa-10-12300918",
        "rarity": "Uncommon"
      },
      {
        "handle": "tornadus-158-psa-10-9647436",
        "rarity": "Uncommon"
      },
      {
        "handle": "leafeon-vstar-210-psa-10-4447684",
        "rarity": "Uncommon"
      },
      {
        "handle": "meowth-ex-100-psa-10-11760288",
        "rarity": "Uncommon"
      },
      {
        "handle": "pikachu-242-sv-p-psa-10-8844131",
        "rarity": "Uncommon"
      },
      {
        "handle": "solosis-123-psa-10-9683005",
        "rarity": "Common"
      },
      {
        "handle": "snivy-87-psa-10-9647330",
        "rarity": "Common"
      },
      {
        "handle": "sawk-128-psa-10-9683129",
        "rarity": "Common"
      },
      {
        "handle": "mega-kangaskhan-ex-89-psa-10-10085342",
        "rarity": "Common"
      },
      {
        "handle": "minccino-157-psa-10-9683053",
        "rarity": "Common"
      },
      {
        "handle": "haxorus-152-psa-10-9683049",
        "rarity": "Common"
      },
      {
        "handle": "espeon-master-ball-62-psa-10-7980427",
        "rarity": "Common"
      },
      {
        "handle": "delphox-v-173-psa-10-4050090",
        "rarity": "Common"
      },
      {
        "handle": "lilligant-92-psa-10-9647453",
        "rarity": "Common"
      },
      {
        "handle": "cubchoo-113-psa-10-9682995",
        "rarity": "Common"
      },
      {
        "handle": "lillipup-153-psa-10-9688434",
        "rarity": "Common"
      }
    ]
  },
  {
    "slug": "gold-pack",
    "title": "Gold Pack",
    "price": 1200,
    "buyback_percent": 90,
    "image": "/images/polycards/gold-pack.webp",
    "display_image": "/images/polycards/gold-factory.webp",
    "rank": 2,
    "cards": [
      {
        "handle": "pikachu-ex-1st-edition-94-psa-10-3506822",
        "rarity": "Immortal"
      },
      {
        "handle": "gengar-ex-1st-edition-90-psa-10-3507567",
        "rarity": "Immortal"
      },
      {
        "handle": "latias-latios-gx-105-psa-10-3468793",
        "rarity": "Immortal"
      },
      {
        "handle": "ooyama-s-pikachu-series-iii-25-psa-10-3473852",
        "rarity": "Immortal"
      },
      {
        "handle": "mew-ex-1st-edition-24-psa-10-4723460",
        "rarity": "Immortal"
      },
      {
        "handle": "pikachu-ex-764-psa-10-11463099",
        "rarity": "Legendary"
      },
      {
        "handle": "mega-gengar-ex-284-psa-10-11816195",
        "rarity": "Legendary"
      },
      {
        "handle": "rowlet-290-sm-p-psa-10-4683337",
        "rarity": "Legendary"
      },
      {
        "handle": "gyarados-ex-89-psa-10-3462587",
        "rarity": "Legendary"
      },
      {
        "handle": "hoopa-155-xy-p-psa-10-4188987",
        "rarity": "Legendary"
      },
      {
        "handle": "gardevoir-sylveon-gx-61-psa-10-3469236",
        "rarity": "Legendary"
      },
      {
        "handle": "charizard-1-psa-10-3684127",
        "rarity": "Mythical"
      },
      {
        "handle": "roaring-moon-ex-162-psa-10-8244605",
        "rarity": "Mythical"
      },
      {
        "handle": "pikachu-tg05-psa-10-4080757",
        "rarity": "Mythical"
      },
      {
        "handle": "rayquaza-gx-177a-psa-10-2390421",
        "rarity": "Mythical"
      },
      {
        "handle": "mega-lucario-ex-92-psa-10-10117206",
        "rarity": "Mythical"
      },
      {
        "handle": "mega-gardevoir-ex-92-psa-10-10117212",
        "rarity": "Mythical"
      },
      {
        "handle": "greninja-ex-90-psa-10-6526274",
        "rarity": "Rare"
      },
      {
        "handle": "giratina-vstar-261-psa-10-4447735",
        "rarity": "Rare"
      },
      {
        "handle": "pikachu-vmax-tg17-psa-10-4080769",
        "rarity": "Rare"
      },
      {
        "handle": "reshiram-charizard-gx-20-psa-10-963176",
        "rarity": "Rare"
      },
      {
        "handle": "hiroshima-s-pikachu-261-sv-p-psa-10-10605024",
        "rarity": "Rare"
      },
      {
        "handle": "sylveon-ex-212-psa-10-7980830",
        "rarity": "Uncommon"
      },
      {
        "handle": "lillie-s-clefairy-ex-126-psa-10-8437204",
        "rarity": "Uncommon"
      },
      {
        "handle": "team-rocket-s-moltres-ex-124-psa-10-9090613",
        "rarity": "Uncommon"
      },
      {
        "handle": "pikachu-173-psa-10-5326214",
        "rarity": "Common"
      },
      {
        "handle": "palkia-ex-7-psa-10-5253065",
        "rarity": "Common"
      },
      {
        "handle": "leafeon-ex-200-psa-10-8054193",
        "rarity": "Common"
      },
      {
        "handle": "glaceon-ex-206-psa-10-7980823",
        "rarity": "Common"
      },
      {
        "handle": "team-rocket-s-nidoking-ex-126-psa-10-9090615",
        "rarity": "Common"
      }
    ]
  },
  {
    "slug": "platinum-pack",
    "title": "Platinum Pack",
    "price": 2500,
    "buyback_percent": 92,
    "image": "/images/polycards/platinum-pack.webp",
    "display_image": "/images/polycards/platinum-factory.webp",
    "rank": 3,
    "cards": [
      {
        "handle": "poncho-wearing-pikachu-charizard-208-xy-p-psa-10-4856869",
        "rarity": "Immortal"
      },
      {
        "handle": "poncho-wearing-pikachu-231-xy-p-psa-10-2812854",
        "rarity": "Immortal"
      },
      {
        "handle": "luigi-pikachu-296-xy-p-psa-10-5047630",
        "rarity": "Immortal"
      },
      {
        "handle": "latias-latios-gx-170-psa-10-962968",
        "rarity": "Immortal"
      },
      {
        "handle": "umbreon-68-psa-10-3438471",
        "rarity": "Legendary"
      },
      {
        "handle": "pikachu-227-s-p-psa-10-4199649",
        "rarity": "Legendary"
      },
      {
        "handle": "easter-pikachu-55-sm-p-psa-10-5769157",
        "rarity": "Legendary"
      },
      {
        "handle": "team-magma-s-groudon-ex-15-psa-10-3445235",
        "rarity": "Legendary"
      },
      {
        "handle": "giratina-v-186-psa-10-4050103",
        "rarity": "Legendary"
      },
      {
        "handle": "gengar-mimikyu-gx-103-psa-10-3468791",
        "rarity": "Legendary"
      },
      {
        "handle": "reshiram-1st-edition-22-psa-10-4723458",
        "rarity": "Legendary"
      },
      {
        "handle": "rayquaza-v-76-psa-10-3472904",
        "rarity": "Mythical"
      },
      {
        "handle": "charizard-vstar-swsh262-psa-10-4246447",
        "rarity": "Mythical"
      },
      {
        "handle": "darkrai-ex-72-psa-10-3460952",
        "rarity": "Mythical"
      },
      {
        "handle": "charizard-gx-sv49-psa-10-964133",
        "rarity": "Mythical"
      },
      {
        "handle": "pikachu-holo-1st-edition-7-psa-10-4723443",
        "rarity": "Mythical"
      },
      {
        "handle": "roaring-moon-ex-162-psa-10-8244605",
        "rarity": "Rare"
      },
      {
        "handle": "pikachu-tg05-psa-10-4080757",
        "rarity": "Rare"
      },
      {
        "handle": "rayquaza-gx-177a-psa-10-2390421",
        "rarity": "Rare"
      },
      {
        "handle": "mega-lucario-ex-92-psa-10-10117206",
        "rarity": "Rare"
      },
      {
        "handle": "mega-gardevoir-ex-92-psa-10-10117212",
        "rarity": "Rare"
      },
      {
        "handle": "rayquaza-vmax-tg20-psa-10-4277108",
        "rarity": "Uncommon"
      },
      {
        "handle": "pikachu-ex-234-psa-10-11302600",
        "rarity": "Uncommon"
      },
      {
        "handle": "mew-30-psa-10-3449699",
        "rarity": "Uncommon"
      },
      {
        "handle": "charizard-ex-349-psa-10-6125394",
        "rarity": "Uncommon"
      },
      {
        "handle": "mew-ex-205-psa-10-5809586",
        "rarity": "Common"
      },
      {
        "handle": "pikachu-v-104-psa-10-3472139",
        "rarity": "Common"
      },
      {
        "handle": "magikarp-80-psa-10-4947437",
        "rarity": "Common"
      },
      {
        "handle": "detective-pikachu-14-psa-10-4034126",
        "rarity": "Common"
      },
      {
        "handle": "mega-greninja-ex-114-psa-10-12271092",
        "rarity": "Common"
      }
    ]
  },
  {
    "slug": "diamond-pack",
    "title": "Diamond Pack",
    "price": 5000,
    "buyback_percent": 92,
    "image": "/images/polycards/diamond-pack.webp",
    "display_image": "/images/polycards/diamond-factory.webp",
    "rank": 4,
    "cards": [
      {
        "handle": "charizard-ex-105-psa-10-850072",
        "rarity": "Immortal"
      },
      {
        "handle": "pikachu-gold-star-1-psa-10-5491689",
        "rarity": "Immortal"
      },
      {
        "handle": "charizard-gold-star-1st-edition-52-psa-10-9866070",
        "rarity": "Immortal"
      },
      {
        "handle": "pikachu-20th-anniversary-festa-279-xy-p-psa-10-2740820",
        "rarity": "Immortal"
      },
      {
        "handle": "mario-pikachu-294-xy-p-psa-10-4956613",
        "rarity": "Immortal"
      },
      {
        "handle": "gengar-ex-1st-edition-90-psa-10-3507567",
        "rarity": "Legendary"
      },
      {
        "handle": "ooyama-s-pikachu-series-iii-25-psa-10-3473852",
        "rarity": "Legendary"
      },
      {
        "handle": "mew-ex-1st-edition-24-psa-10-4723460",
        "rarity": "Legendary"
      },
      {
        "handle": "luigi-pikachu-295-xy-p-psa-10-5058483",
        "rarity": "Legendary"
      },
      {
        "handle": "rayquaza-vmax-83-psa-10-3472911",
        "rarity": "Legendary"
      },
      {
        "handle": "pikachu-ex-xy84-psa-10-844750",
        "rarity": "Legendary"
      },
      {
        "handle": "team-magma-s-groudon-ex-15-psa-10-3445235",
        "rarity": "Mythical"
      },
      {
        "handle": "giratina-v-186-psa-10-4050103",
        "rarity": "Mythical"
      },
      {
        "handle": "gengar-mimikyu-gx-103-psa-10-3468791",
        "rarity": "Mythical"
      },
      {
        "handle": "reshiram-1st-edition-22-psa-10-4723458",
        "rarity": "Mythical"
      },
      {
        "handle": "flareon-ex-7-psa-10-4557547",
        "rarity": "Mythical"
      },
      {
        "handle": "sylveon-ex-26-psa-10-4557566",
        "rarity": "Mythical"
      },
      {
        "handle": "mewtwo-mew-gx-98-psa-10-3470024",
        "rarity": "Mythical"
      },
      {
        "handle": "charizard-vstar-swsh262-psa-10-4246447",
        "rarity": "Rare"
      },
      {
        "handle": "charizard-gx-sv49-psa-10-964133",
        "rarity": "Rare"
      },
      {
        "handle": "pikachu-holo-1st-edition-7-psa-10-4723443",
        "rarity": "Rare"
      },
      {
        "handle": "mewtwo-3-psa-10-643534",
        "rarity": "Rare"
      },
      {
        "handle": "pretend-comedian-pikachu-407-sm-p-psa-10-4225263",
        "rarity": "Uncommon"
      },
      {
        "handle": "umbreon-gx-229-psa-10-3445777",
        "rarity": "Uncommon"
      },
      {
        "handle": "s-pikachu-7-psa-10-3684133",
        "rarity": "Uncommon"
      },
      {
        "handle": "eevee-gx-188-psa-10-4118654",
        "rarity": "Uncommon"
      },
      {
        "handle": "mew-ex-347-psa-10-6125392",
        "rarity": "Uncommon"
      },
      {
        "handle": "mewtwo-vstar-gg44-psa-10-4637100",
        "rarity": "Common"
      },
      {
        "handle": "reshiram-ex-166-psa-10-10026819",
        "rarity": "Common"
      },
      {
        "handle": "pikachu-205-psa-10-4447679",
        "rarity": "Common"
      }
    ]
  }
];
