// Canonical VIP ladder — parsed from Workbook1.xlsx (boss's authoritative sheet),
// thresholds rounded to whole MYR. Single source of truth for the seed. Resolved
// 2026-06-20: L40 direct_referral_pct = 4 (no blank); L50 voucher = 300 (confirmed);
// thresholds whole-MYR. Do NOT edit values without re-confirming against the workbook.
export type VipLevelSeed = {
  level: number;
  spend_threshold: number;
  voucher_amount: number;
  box_tier: string;
  frame_unlock: boolean;
  direct_referral_pct: number;
  prizes: null;
};

export const VIP_LEVELS: readonly VipLevelSeed[] = Object.freeze([
  {
    level: 1,
    spend_threshold: 0,
    voucher_amount: 0,
    box_tier: 'a',
    frame_unlock: false,
    direct_referral_pct: 1,
    prizes: null,
  },
  {
    level: 2,
    spend_threshold: 3,
    voucher_amount: 2,
    box_tier: 'a',
    frame_unlock: false,
    direct_referral_pct: 1,
    prizes: null,
  },
  {
    level: 3,
    spend_threshold: 25,
    voucher_amount: 2,
    box_tier: 'a',
    frame_unlock: false,
    direct_referral_pct: 1,
    prizes: null,
  },
  {
    level: 4,
    spend_threshold: 83,
    voucher_amount: 2,
    box_tier: 'a',
    frame_unlock: false,
    direct_referral_pct: 1,
    prizes: null,
  },
  {
    level: 5,
    spend_threshold: 198,
    voucher_amount: 2,
    box_tier: 'a',
    frame_unlock: false,
    direct_referral_pct: 1,
    prizes: null,
  },
  {
    level: 6,
    spend_threshold: 386,
    voucher_amount: 2,
    box_tier: 'a',
    frame_unlock: false,
    direct_referral_pct: 1,
    prizes: null,
  },
  {
    level: 7,
    spend_threshold: 668,
    voucher_amount: 5,
    box_tier: 'a',
    frame_unlock: false,
    direct_referral_pct: 1,
    prizes: null,
  },
  {
    level: 8,
    spend_threshold: 1060,
    voucher_amount: 5,
    box_tier: 'a',
    frame_unlock: false,
    direct_referral_pct: 1,
    prizes: null,
  },
  {
    level: 9,
    spend_threshold: 1583,
    voucher_amount: 5,
    box_tier: 'a',
    frame_unlock: false,
    direct_referral_pct: 1,
    prizes: null,
  },
  {
    level: 10,
    spend_threshold: 2254,
    voucher_amount: 50,
    box_tier: 'b',
    frame_unlock: true,
    direct_referral_pct: 2,
    prizes: null,
  },
  {
    level: 11,
    spend_threshold: 3092,
    voucher_amount: 10,
    box_tier: 'b',
    frame_unlock: false,
    direct_referral_pct: 2,
    prizes: null,
  },
  {
    level: 12,
    spend_threshold: 4115,
    voucher_amount: 10,
    box_tier: 'b',
    frame_unlock: false,
    direct_referral_pct: 2,
    prizes: null,
  },
  {
    level: 13,
    spend_threshold: 5343,
    voucher_amount: 10,
    box_tier: 'b',
    frame_unlock: false,
    direct_referral_pct: 2,
    prizes: null,
  },
  {
    level: 14,
    spend_threshold: 6793,
    voucher_amount: 10,
    box_tier: 'b',
    frame_unlock: false,
    direct_referral_pct: 2,
    prizes: null,
  },
  {
    level: 15,
    spend_threshold: 8484,
    voucher_amount: 10,
    box_tier: 'b',
    frame_unlock: false,
    direct_referral_pct: 2,
    prizes: null,
  },
  {
    level: 16,
    spend_threshold: 10435,
    voucher_amount: 10,
    box_tier: 'b',
    frame_unlock: false,
    direct_referral_pct: 2,
    prizes: null,
  },
  {
    level: 17,
    spend_threshold: 12664,
    voucher_amount: 10,
    box_tier: 'b',
    frame_unlock: false,
    direct_referral_pct: 2,
    prizes: null,
  },
  {
    level: 18,
    spend_threshold: 15190,
    voucher_amount: 10,
    box_tier: 'b',
    frame_unlock: false,
    direct_referral_pct: 2,
    prizes: null,
  },
  {
    level: 19,
    spend_threshold: 18032,
    voucher_amount: 10,
    box_tier: 'b',
    frame_unlock: false,
    direct_referral_pct: 2,
    prizes: null,
  },
  {
    level: 20,
    spend_threshold: 21207,
    voucher_amount: 300,
    box_tier: 'c',
    frame_unlock: true,
    direct_referral_pct: 3,
    prizes: null,
  },
  {
    level: 21,
    spend_threshold: 24735,
    voucher_amount: 88,
    box_tier: 'c',
    frame_unlock: false,
    direct_referral_pct: 3,
    prizes: null,
  },
  {
    level: 22,
    spend_threshold: 28633,
    voucher_amount: 88,
    box_tier: 'c',
    frame_unlock: false,
    direct_referral_pct: 3,
    prizes: null,
  },
  {
    level: 23,
    spend_threshold: 32922,
    voucher_amount: 88,
    box_tier: 'c',
    frame_unlock: false,
    direct_referral_pct: 3,
    prizes: null,
  },
  {
    level: 24,
    spend_threshold: 37618,
    voucher_amount: 88,
    box_tier: 'c',
    frame_unlock: false,
    direct_referral_pct: 3,
    prizes: null,
  },
  {
    level: 25,
    spend_threshold: 42741,
    voucher_amount: 88,
    box_tier: 'c',
    frame_unlock: false,
    direct_referral_pct: 3,
    prizes: null,
  },
  {
    level: 26,
    spend_threshold: 48310,
    voucher_amount: 88,
    box_tier: 'c',
    frame_unlock: false,
    direct_referral_pct: 3,
    prizes: null,
  },
  {
    level: 27,
    spend_threshold: 54342,
    voucher_amount: 88,
    box_tier: 'c',
    frame_unlock: false,
    direct_referral_pct: 3,
    prizes: null,
  },
  {
    level: 28,
    spend_threshold: 60856,
    voucher_amount: 88,
    box_tier: 'c',
    frame_unlock: false,
    direct_referral_pct: 3,
    prizes: null,
  },
  {
    level: 29,
    spend_threshold: 67872,
    voucher_amount: 88,
    box_tier: 'c',
    frame_unlock: false,
    direct_referral_pct: 3,
    prizes: null,
  },
  {
    level: 30,
    spend_threshold: 75407,
    voucher_amount: 888,
    box_tier: 'd',
    frame_unlock: true,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 31,
    spend_threshold: 83479,
    voucher_amount: 120,
    box_tier: 'd',
    frame_unlock: false,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 32,
    spend_threshold: 92109,
    voucher_amount: 120,
    box_tier: 'd',
    frame_unlock: false,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 33,
    spend_threshold: 101313,
    voucher_amount: 120,
    box_tier: 'd',
    frame_unlock: false,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 34,
    spend_threshold: 111111,
    voucher_amount: 120,
    box_tier: 'd',
    frame_unlock: false,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 35,
    spend_threshold: 121521,
    voucher_amount: 120,
    box_tier: 'd',
    frame_unlock: false,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 36,
    spend_threshold: 132562,
    voucher_amount: 120,
    box_tier: 'd',
    frame_unlock: false,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 37,
    spend_threshold: 144252,
    voucher_amount: 120,
    box_tier: 'd',
    frame_unlock: false,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 38,
    spend_threshold: 156610,
    voucher_amount: 120,
    box_tier: 'd',
    frame_unlock: false,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 39,
    spend_threshold: 169655,
    voucher_amount: 120,
    box_tier: 'd',
    frame_unlock: false,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 40,
    spend_threshold: 183404,
    voucher_amount: 1200,
    box_tier: 'e',
    frame_unlock: true,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 41,
    spend_threshold: 197877,
    voucher_amount: 300,
    box_tier: 'e',
    frame_unlock: false,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 42,
    spend_threshold: 213092,
    voucher_amount: 300,
    box_tier: 'e',
    frame_unlock: false,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 43,
    spend_threshold: 229068,
    voucher_amount: 300,
    box_tier: 'e',
    frame_unlock: false,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 44,
    spend_threshold: 245822,
    voucher_amount: 300,
    box_tier: 'e',
    frame_unlock: false,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 45,
    spend_threshold: 263374,
    voucher_amount: 300,
    box_tier: 'e',
    frame_unlock: false,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 46,
    spend_threshold: 281743,
    voucher_amount: 300,
    box_tier: 'e',
    frame_unlock: false,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 47,
    spend_threshold: 300946,
    voucher_amount: 300,
    box_tier: 'e',
    frame_unlock: false,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 48,
    spend_threshold: 321003,
    voucher_amount: 300,
    box_tier: 'e',
    frame_unlock: false,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 49,
    spend_threshold: 341932,
    voucher_amount: 300,
    box_tier: 'e',
    frame_unlock: false,
    direct_referral_pct: 4,
    prizes: null,
  },
  {
    level: 50,
    spend_threshold: 363751,
    voucher_amount: 300,
    box_tier: 'f',
    frame_unlock: true,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 51,
    spend_threshold: 386479,
    voucher_amount: 300,
    box_tier: 'f',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 52,
    spend_threshold: 410134,
    voucher_amount: 300,
    box_tier: 'f',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 53,
    spend_threshold: 434736,
    voucher_amount: 300,
    box_tier: 'f',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 54,
    spend_threshold: 460302,
    voucher_amount: 300,
    box_tier: 'f',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 55,
    spend_threshold: 486852,
    voucher_amount: 300,
    box_tier: 'f',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 56,
    spend_threshold: 514403,
    voucher_amount: 300,
    box_tier: 'f',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 57,
    spend_threshold: 542975,
    voucher_amount: 300,
    box_tier: 'f',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 58,
    spend_threshold: 572585,
    voucher_amount: 300,
    box_tier: 'f',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 59,
    spend_threshold: 603253,
    voucher_amount: 300,
    box_tier: 'f',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 60,
    spend_threshold: 634997,
    voucher_amount: 3000,
    box_tier: 'g',
    frame_unlock: true,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 61,
    spend_threshold: 667835,
    voucher_amount: 500,
    box_tier: 'g',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 62,
    spend_threshold: 701787,
    voucher_amount: 500,
    box_tier: 'g',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 63,
    spend_threshold: 736870,
    voucher_amount: 500,
    box_tier: 'g',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 64,
    spend_threshold: 773103,
    voucher_amount: 500,
    box_tier: 'g',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 65,
    spend_threshold: 810505,
    voucher_amount: 500,
    box_tier: 'g',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 66,
    spend_threshold: 849094,
    voucher_amount: 500,
    box_tier: 'g',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 67,
    spend_threshold: 888889,
    voucher_amount: 500,
    box_tier: 'g',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 68,
    spend_threshold: 929908,
    voucher_amount: 500,
    box_tier: 'g',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 69,
    spend_threshold: 972170,
    voucher_amount: 500,
    box_tier: 'g',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 70,
    spend_threshold: 1015694,
    voucher_amount: 5000,
    box_tier: 'h',
    frame_unlock: true,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 71,
    spend_threshold: 1060498,
    voucher_amount: 800,
    box_tier: 'h',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 72,
    spend_threshold: 1106600,
    voucher_amount: 800,
    box_tier: 'h',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 73,
    spend_threshold: 1154020,
    voucher_amount: 800,
    box_tier: 'h',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 74,
    spend_threshold: 1202775,
    voucher_amount: 800,
    box_tier: 'h',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 75,
    spend_threshold: 1252884,
    voucher_amount: 800,
    box_tier: 'h',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 76,
    spend_threshold: 1304366,
    voucher_amount: 800,
    box_tier: 'h',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 77,
    spend_threshold: 1357239,
    voucher_amount: 800,
    box_tier: 'h',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 78,
    spend_threshold: 1411523,
    voucher_amount: 800,
    box_tier: 'h',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 79,
    spend_threshold: 1467234,
    voucher_amount: 800,
    box_tier: 'h',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 80,
    spend_threshold: 1524393,
    voucher_amount: 8000,
    box_tier: 'i',
    frame_unlock: true,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 81,
    spend_threshold: 1583017,
    voucher_amount: 1200,
    box_tier: 'i',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 82,
    spend_threshold: 1643125,
    voucher_amount: 1200,
    box_tier: 'i',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 83,
    spend_threshold: 1704736,
    voucher_amount: 1200,
    box_tier: 'i',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 84,
    spend_threshold: 1767868,
    voucher_amount: 1200,
    box_tier: 'i',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 85,
    spend_threshold: 1832540,
    voucher_amount: 1200,
    box_tier: 'i',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 86,
    spend_threshold: 1898770,
    voucher_amount: 1200,
    box_tier: 'i',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 87,
    spend_threshold: 1966577,
    voucher_amount: 1200,
    box_tier: 'i',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 88,
    spend_threshold: 2035980,
    voucher_amount: 1200,
    box_tier: 'i',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 89,
    spend_threshold: 2106996,
    voucher_amount: 1200,
    box_tier: 'i',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 90,
    spend_threshold: 2179645,
    voucher_amount: 12000,
    box_tier: 'j',
    frame_unlock: true,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 91,
    spend_threshold: 2253944,
    voucher_amount: 1500,
    box_tier: 'j',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 92,
    spend_threshold: 2329914,
    voucher_amount: 1500,
    box_tier: 'j',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 93,
    spend_threshold: 2407571,
    voucher_amount: 1500,
    box_tier: 'j',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 94,
    spend_threshold: 2486935,
    voucher_amount: 1500,
    box_tier: 'j',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 95,
    spend_threshold: 2568025,
    voucher_amount: 1500,
    box_tier: 'j',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 96,
    spend_threshold: 2650858,
    voucher_amount: 1500,
    box_tier: 'j',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 97,
    spend_threshold: 2735454,
    voucher_amount: 1500,
    box_tier: 'j',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 98,
    spend_threshold: 2821830,
    voucher_amount: 1500,
    box_tier: 'j',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 99,
    spend_threshold: 2910006,
    voucher_amount: 1500,
    box_tier: 'j',
    frame_unlock: false,
    direct_referral_pct: 5,
    prizes: null,
  },
  {
    level: 100,
    spend_threshold: 3000000,
    voucher_amount: 15000,
    box_tier: 'Z',
    frame_unlock: true,
    direct_referral_pct: 5,
    prizes: null,
  },
]);

if (new Set(VIP_LEVELS.map((r) => r.level)).size !== VIP_LEVELS.length) {
  throw new Error('VIP_LEVELS contains duplicate levels');
}

// What actually gets INSERTED. Vouchers are off across the ladder (operator
// decision 2026-08-05: the redeeming surface is suspended, so a level-up was
// minting grants nobody could spend — Migration20260805000000 zeroed the live
// rows). Seeding straight from VIP_LEVELS would hand a fresh environment the
// payouts the migration exists to remove.
//
// VIP_LEVELS itself keeps the workbook figures: it is the record of Workbook1
// (see the header), the parity tests assert against it, and turning a payout
// back on should be reading the sheet, not archaeology on a seed script.
export const VIP_LEVELS_SEED: readonly VipLevelSeed[] = Object.freeze(
  VIP_LEVELS.map((r) => Object.freeze({ ...r, voucher_amount: 0 })),
);
