import { Migration } from "@medusajs/framework/mikro-orm/migrations";

// Phase 2a Task 12 — commission lifecycle record + generation column on ledger.
// Generated by `db:generate packs` then normalized to timestamp 160000.
// The partial-unique idempotency index lives in Migration20260622161000.ts
// (hand-written; db:generate can't produce expression partial-unique indexes).
export class Migration20260622160000 extends Migration {

  override async up(): Promise<void> {
    this.addSql(`alter table if exists "commission" drop constraint if exists "commission_credit_transaction_id_unique";`);
    this.addSql(`create table if not exists "commission" ("id" text not null, "credit_transaction_id" text not null, "beneficiary" text not null, "source_transaction_id" text not null, "generation" integer not null, "kind" text check ("kind" in ('direct', 'override')) not null default 'direct', "status" text check ("status" in ('pending', 'available', 'suspended', 'reversed')) not null default 'pending', "matures_at" timestamptz not null, "effective_pct" integer not null, "reversal_transaction_id" text null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "commission_pkey" primary key ("id"));`);
    this.addSql(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_commission_credit_transaction_id_unique" ON "commission" ("credit_transaction_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_commission_deleted_at" ON "commission" ("deleted_at") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_commission_beneficiary" ON "commission" ("beneficiary") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_commission_source_transaction_id" ON "commission" ("source_transaction_id") WHERE deleted_at IS NULL;`);

    this.addSql(`alter table if exists "credit_transaction" add column if not exists "generation" integer null;`);
  }

  override async down(): Promise<void> {
    this.addSql(`drop table if exists "commission" cascade;`);

    this.addSql(`alter table if exists "credit_transaction" drop column if exists "generation";`);
  }

}
