import { medusaIntegrationTestRunner } from '@medusajs/test-utils';
import { PACKS_MODULE } from '../../src/modules/packs';
import type PacksModuleService from '../../src/modules/packs/service';
import { settlementSince } from '../../src/modules/packs/globepay-settlement';
import { mintSuperAdmin, unwrapResponse } from './utils';

jest.setTimeout(240 * 1000);

// GET /admin/globepay/settlement against a REAL database.
//
// WHY integration and not only the unit-tested fold: the report's SQL carries
// three things a mock cannot vouch for — that the new settlement-mirror
// columns (net_amount + raw_net_amount sidecar, Migration20260817090000)
// actually exist and sum; that date_trunc(… AT TIME ZONE 'Asia/Kuala_Lumpur')
// agrees with settlementSince's fixed-+8 arithmetic about which bucket an
// instant belongs to (two month conventions here would shear buckets); and
// that the FILTER-based known-net fee math survives numeric/bigint casting.
// The fold itself is pinned in
// src/modules/packs/__tests__/globepay-settlement.unit.spec.ts.
//
// TIMELESS ON PURPOSE: the ledger rows seeded below get their created_at from
// the database (no reliable override through the autogenerated create), so
// every fixture is anchored to the CURRENT MYT month — computed through the
// same settlementSince the route uses — rather than to a hardcoded August
// that goes stale the day the calendar turns.
const PASSWORD = 'globepay-settlement-password-1'; // gitleaks:allow
const ADMIN_EMAIL = 'globepay-settlement-admin@test.dev';
const CUSTOMER_ID = 'cus_globepay_settlement';

const MYT_OFFSET_MS = 8 * 60 * 60 * 1000;
const HOUR_MS = 60 * 60 * 1000;

// Start of the current MYT month as a UTC instant, its 'YYYY-MM-DD' bucket
// key, and the same pair for the NEXT month (the rollover probe).
const monthStart = settlementSince('month', 1, new Date());
const keyOf = (utcStart: Date): string =>
  new Date(utcStart.getTime() + MYT_OFFSET_MS).toISOString().slice(0, 10);
const CURRENT_KEY = keyOf(monthStart);
const mytMonthStartPlus = (months: number): Date => {
  const myt = new Date(monthStart.getTime() + MYT_OFFSET_MS);
  return new Date(
    Date.UTC(myt.getUTCFullYear(), myt.getUTCMonth() + months, 1) -
      MYT_OFFSET_MS,
  );
};
const NEXT_START = mytMonthStartPlus(1);
const NEXT_KEY = keyOf(NEXT_START);
// Safely inside the current MYT month whatever today is (day 2, 02:00 MYT).
const MID_MONTH = new Date(monthStart.getTime() + 26 * HOUR_MS);
// 04:00 MYT on the 1st of the NEXT month — a future settled_at buckets fine;
// date_trunc has no opinion about the future.
const ROLLOVER = new Date(NEXT_START.getTime() + 4 * HOUR_MS);

medusaIntegrationTestRunner({
  inApp: true,
  testSuite: ({ api, getContainer }) => {
    describe('GET /admin/globepay/settlement', () => {
      let adminToken: string;

      const packs = (): PacksModuleService =>
        getContainer().resolve<PacksModuleService>(PACKS_MODULE);

      beforeEach(async () => {
        adminToken = await mintSuperAdmin(
          getContainer(),
          api,
          ADMIN_EMAIL,
          PASSWORD,
        );
      });

      const report = async (qs: string) => {
        const res = await unwrapResponse(
          api.get(`/admin/globepay/settlement${qs}`, {
            headers: { authorization: `Bearer ${adminToken}` },
          }),
        );
        expect(res.status).toBe(200);
        return res.data as {
          granularity: string;
          periods: {
            period: string;
            deposits: {
              count: number;
              gross: number;
              net: number;
              fee: number;
              missingNet: number;
              missingGross: number;
            };
            withdrawals: { count: number; gross: number; fee: number };
            ledger: { topupCredited: number; cashoutNet: number };
            delta: { deposits: number; withdrawals: number };
          }[];
        };
      };

      it('buckets by MYT calendar month, sums net-known fees, and cross-checks the ledger', async () => {
        // Two settled deposits this MYT month: RM 100 with net 97 on file,
        // RM 50 settled pre-mirror (net unknown). A third settles at 04:00 MYT
        // on the 1st of NEXT month — it must not leak into this month.
        await packs().createGlobePayDeposits([
          {
            merchant_transaction_id: 'PC-settle-cur-1',
            customer_id: CUSTOMER_ID,
            amount_requested: 100,
            amount_settled: 100,
            net_amount: 97,
            payment_method_code: 'BQR',
            status: 'settled',
            settled_at: MID_MONTH,
          },
          {
            merchant_transaction_id: 'PC-settle-cur-2',
            customer_id: CUSTOMER_ID,
            amount_requested: 50,
            amount_settled: 50,
            payment_method_code: 'BQR',
            status: 'settled',
            settled_at: MID_MONTH,
          },
          {
            merchant_transaction_id: 'PC-settle-next',
            customer_id: CUSTOMER_ID,
            amount_requested: 30,
            amount_settled: 30,
            net_amount: 29,
            payment_method_code: 'BQR',
            status: 'settled',
            settled_at: ROLLOVER,
          },
          // Pending rows must not count at all.
          {
            merchant_transaction_id: 'PC-settle-pending',
            customer_id: CUSTOMER_ID,
            amount_requested: 999,
            payment_method_code: 'BQR',
            status: 'pending',
          },
        ]);

        // A settled payout with net on file, same month.
        await packs().createGlobePayWithdrawals([
          {
            merchant_transaction_id: 'PC-settle-wd-1',
            customer_id: CUSTOMER_ID,
            amount: 80,
            amount_settled: 80,
            net_amount: 78,
            bank_code: 'MBB',
            account_number: '1234567890',
            account_holder_name: 'SETTLEMENT SPEC',
            status: 'settled',
            settled_at: MID_MONTH,
          },
        ]);

        // The ledger's view of the same flows. created_at = now, which is by
        // construction inside the current MYT month bucket.
        await packs().createCreditTransactions([
          {
            customer_id: CUSTOMER_ID,
            amount: 150,
            reason: 'topup' as const,
            pull_id: null,
            reference: 'settle-spec-topup',
          },
          {
            customer_id: CUSTOMER_ID,
            amount: -80,
            reason: 'cashout' as const,
            pull_id: null,
            reference: 'settle-spec-cashout',
          },
        ] as Parameters<PacksModuleService['createCreditTransactions']>[0]);

        const data = await report('?granularity=month&periods=12');
        expect(data.granularity).toBe('month');

        const current = data.periods.find((p) => p.period === CURRENT_KEY);
        expect(current).toBeDefined();
        // Gross counts BOTH settled rows; net/fee only the known-net one —
        // fee 3 (100 − 97), never 53 (150 − 97). The pending row is invisible.
        expect(current!.deposits).toEqual({
          count: 2,
          gross: 150,
          net: 97,
          fee: 3,
          missingNet: 1,
          missingGross: 0,
        });
        expect(current!.withdrawals.count).toBe(1);
        expect(current!.withdrawals.gross).toBe(80);
        expect(current!.withdrawals.fee).toBe(2);
        // Ledger agrees with the gateway this month: both deltas exactly 0.
        expect(current!.ledger.topupCredited).toBe(150);
        expect(current!.ledger.cashoutNet).toBe(80);
        expect(current!.delta.deposits).toBe(0);
        expect(current!.delta.withdrawals).toBe(0);

        // The MYT rollover row belongs to the NEXT month bucket.
        const next = data.periods.find((p) => p.period === NEXT_KEY);
        expect(next).toBeDefined();
        expect(next!.deposits.count).toBe(1);
        expect(next!.deposits.gross).toBe(30);
      });

      // The case the unit-tested fold can never reach: this proves the SQL
      // FILTER itself (missing_gross, service.ts globepaySettlementRows)
      // exists and casts correctly against a real Postgres, not just the pure
      // merge over already-shaped rows. Uses its own period (3 months back,
      // still inside periods=12) so its totals are exact regardless of what
      // the other cases in this file seed into the current/next-month/current
      // -week buckets.
      it('a settled deposit with NULL amount_settled is counted but excluded from gross — missingGross', async () => {
        const priorStart = mytMonthStartPlus(-3);
        const priorKey = keyOf(priorStart);
        const priorMid = new Date(priorStart.getTime() + 26 * HOUR_MS);

        await packs().createGlobePayDeposits([
          {
            merchant_transaction_id: 'PC-settle-missgross-1',
            customer_id: CUSTOMER_ID,
            amount_requested: 60,
            amount_settled: 60,
            payment_method_code: 'BQR',
            status: 'settled',
            settled_at: priorMid,
          },
          // Hand-settled outside every writer that sets amount_settled — the
          // quarantine → manual-settlement path (money-path-accuracy-audit-
          // 2026-08-17). No net_amount either: a real hand-settled row has
          // neither, same as PC-settle-cur-2 models for missingNet above.
          {
            merchant_transaction_id: 'PC-settle-missgross-2',
            customer_id: CUSTOMER_ID,
            amount_requested: 999,
            payment_method_code: 'BQR',
            status: 'settled',
            settled_at: priorMid,
          },
        ]);

        const data = await report('?granularity=month&periods=12');
        const period = data.periods.find((p) => p.period === priorKey);
        expect(period).toBeDefined();
        // Both settled rows count; only the priced one's amount lands in
        // gross — the NULL row is excluded from the sum, not zeroed into it.
        expect(period!.deposits.count).toBe(2);
        expect(period!.deposits.gross).toBe(60);
        expect(period!.deposits.missingGross).toBe(1);
      });

      it('falls back to month/12 on garbage params instead of erroring', async () => {
        const data = await report('?granularity=quarterly&periods=-3');
        expect(data.granularity).toBe('month');
      });

      // The week convention, against the real database: settlementSince says
      // ISO Monday (fixed +8), Postgres date_trunc('week' …) says ISO Monday
      // (AT TIME ZONE) — if the two ever disagreed, this row would land under
      // a different period key than the one derived here and the find() fails.
      // The month cases above cannot catch that; a month has no weekday
      // convention to shear on.
      it('buckets by MYT ISO week under granularity=week', async () => {
        const weekStart = settlementSince('week', 1, new Date());
        const weekKey = keyOf(weekStart);
        // Day 2 of the current MYT week, 02:00 — inside the bucket whatever
        // today is (future settled_at buckets fine, same as ROLLOVER above).
        const inWeek = new Date(weekStart.getTime() + 26 * HOUR_MS);

        await packs().createGlobePayDeposits([
          {
            merchant_transaction_id: 'PC-settle-week-1',
            customer_id: CUSTOMER_ID,
            amount_requested: 40,
            amount_settled: 40,
            net_amount: 39,
            payment_method_code: 'BQR',
            status: 'settled',
            settled_at: inWeek,
          },
        ]);

        const data = await report('?granularity=week&periods=2');
        expect(data.granularity).toBe('week');
        const week = data.periods.find((p) => p.period === weekKey);
        expect(week).toBeDefined();
        expect(week!.deposits.count).toBe(1);
        expect(week!.deposits.gross).toBe(40);
        expect(week!.deposits.fee).toBe(1);
      });
    });
  },
});
